// Auto-generated by text2code. Do not edit by hand.
// Regenerate with `text2code <pdeapp.txt>`.
//
// This header is consumed by `<exasim/model.hpp>`'s templated FEM
// internals. The struct below satisfies the Model contract; the
// inherited `ModelDefaults<GeneratedModel>` supplies zero-fill
// defaults for any optional method this PDE doesn't define.
#pragma once

#include <Kokkos_Core.hpp>
struct PdeModel : ModelDefaults<PdeModel> {
    static constexpr int nd     = 2;
    static constexpr int ncu    = 4;
    static constexpr int ncw    = 0;
    static constexpr int nco    = 2;
    static constexpr int nparam = 11;
    static constexpr int Nq = ncu * (1 + nd);

    KOKKOS_INLINE_FUNCTION static
    void flux(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uq1, 2);
        const dstype x1 = Kokkos::pow(uq0, -1);
        const dstype x2 = x1*uq2;
        const dstype x3 = uq10 - x2*uq8;
        const dstype x4 = x1*x3;
        const dstype x5 = x1*uq1;
        const dstype x6 = uq5 - x5*uq4;
        const dstype x7 = x1*x6;
        const dstype x8 = -1.0 + mu0;
        const dstype x9 = Kokkos::pow(uq2, 2);
        const dstype x10 = Kokkos::pow(uq0, -2);
        const dstype x11 = 0.5*(x0*x10 + x9*x10);
        const dstype x12 = uq3 - uq0*x11;
        const dstype x13 = x8*x12;
        const dstype x14 = x1*x13;
        const dstype x15 = Kokkos::sqrt(Kokkos::pow(x8, 3)*Kokkos::pow(x12, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3)/Kokkos::pow(uq0, 3))*(110.4 + mu9)/(mu1*(110.4 + 1.0*x14*Kokkos::pow(mu3, 2)*mu9*mu0));
        const dstype x16 = 0.666666666666667*x15;
        const dstype x17 = (-x4 + 2*x7)*x16;
        const dstype x18 = uq6 - x2*uq4;
        const dstype x19 = uq9 - x5*uq8;
        const dstype x20 = 1.0*x15;
        const dstype x21 = (x1*x18 + x1*x19)*x20;
        const dstype x22 = x21 + x5*uq2;
        const dstype x23 = uq2*x10;
        const dstype x24 = uq1*x10;
        const dstype x25 = x8*uq0;
        const dstype x26 = x20*x10*mu0/(x8*mu2);
        const dstype x27 = x14 + x1*uq3;
        const dstype x28 = (2*x4 - x7)*x16;

        f[0] = uq1 + v0*uq4;
        f[1] = x13 + x17 + v0*uq5 + x0*x1;
        f[2] = x22 + v0*uq6;
        f[3] = uq1*x27 + v0*uq7 + x2*x21 + x26*(-uq4*x13 + x25*(uq7 - uq0*(x23*x18 + x6*x24) - uq4*x11)) + x5*x17;
        f[4] = uq2 + v0*uq8;
        f[5] = x22 + v0*uq9;
        f[6] = x13 + x28 + v0*uq10 + x1*x9;
        f[7] = uq2*x27 + v0*uq11 + x2*x28 + x26*(-uq8*x13 + x25*(uq11 - uq0*(x24*x19 + x3*x23) - uq8*x11)) + x5*x21;
    }

    KOKKOS_INLINE_FUNCTION static
    void source(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void tdfunc(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 1;
        f[1] = 1;
        f[2] = 1;
        f[3] = 1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_scalars(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];

        const dstype x0 = Kokkos::pow(uq0, -1);
        const dstype x1 = uq3 - 0.5*(x0*Kokkos::pow(uq1, 2) + x0*Kokkos::pow(uq2, 2));

        f[0] = uq0;
        f[1] = x0*uq1;
        f[2] = x0*uq2;
        f[3] = 0.4*x1;
        f[4] = x0*x1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_vectors(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];

        f[0] = uq1;
        f[1] = uq2;
    }

    KOKKOS_INLINE_FUNCTION static
    void initu(dstype f[], const dstype x[], const dstype uinf[], const dstype mu[]) {
        const dstype mu4 = mu[4];
        const dstype mu5 = mu[5];
        const dstype mu6 = mu[6];
        const dstype mu7 = mu[7];

        f[0] = mu4;
        f[1] = mu5;
        f[2] = mu6;
        f[3] = mu7;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype mu4 = mu[4];
            const dstype mu5 = mu[5];
            const dstype mu6 = mu[6];
            const dstype mu7 = mu[7];

            f[0] = mu4 - uhat0;
            f[1] = mu5 - uhat1;
            f[2] = mu6 - uhat2;
            f[3] = mu7 - uhat3;
        }
        else if (ib == 2) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uq3 = uq[3];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1 + uq1;
            f[2] = -uhat2 + uq2;
            f[3] = -uhat3 + uq3;
        }
        else if (ib == 3) {
            const dstype uq0 = uq[0];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype mu8 = mu[8];
            const dstype mu9 = mu[9];
            const dstype mu10 = mu[10];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1;
            f[2] = -uhat2;
            f[3] = -uhat3 + mu8*mu10*uhat0/mu9;
        }
        else if (ib == 4) {
            const dstype uq0 = uq[0];
            const dstype uq3 = uq[3];
            const dstype uq4 = uq[4];
            const dstype uq5 = uq[5];
            const dstype uq6 = uq[6];
            const dstype uq7 = uq[7];
            const dstype uq8 = uq[8];
            const dstype uq9 = uq[9];
            const dstype uq10 = uq[10];
            const dstype uq11 = uq[11];
            const dstype v0 = v[0];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype mu0 = mu[0];
            const dstype mu1 = mu[1];
            const dstype mu2 = mu[2];
            const dstype mu3 = mu[3];
            const dstype mu9 = mu[9];

            const dstype x0 = Kokkos::pow(uhat0, -1);
            const dstype x1 = x0*uhat1;
            const dstype x2 = uq5 - x1*uq4;
            const dstype x3 = x0*x2;
            const dstype x4 = x0*uhat2;
            const dstype x5 = uq10 - x4*uq8;
            const dstype x6 = x0*x5;
            const dstype x7 = Kokkos::pow(uhat0, -2);
            const dstype x8 = 0.5*(x7*Kokkos::pow(uhat1, 2) + x7*Kokkos::pow(uhat2, 2));
            const dstype x9 = uhat3 - x8*uhat0;
            const dstype x10 = -1.0 + mu0;
            const dstype x11 = x9*x10;
            const dstype x12 = x0*x11;
            const dstype x13 = 1.0*mu0;
            const dstype x14 = Kokkos::sqrt(Kokkos::pow(x9, 3)*Kokkos::pow(x10, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3)/Kokkos::pow(uhat0, 3))*(110.4 + mu9)/(mu1*(110.4 + x13*x12*Kokkos::pow(mu3, 2)*mu9));
            const dstype x15 = 0.666666666666667*x14;
            const dstype x16 = uq6 - x4*uq4;
            const dstype x17 = uq9 - x1*uq8;
            const dstype x18 = 1.0*(x0*x16 + x0*x17)*x14;
            const dstype x19 = x12 + x0*uhat3;
            const dstype x20 = x7*uhat2;
            const dstype x21 = x7*uhat1;
            const dstype x22 = x10*uhat0;
            const dstype x23 = x7*x14*x13/(x10*mu2);

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1;
            f[2] = -uhat2;
            f[3] = n0*(v0*uq7 + x19*uhat1 + x23*(-uq4*x11 + x22*(uq7 - uhat0*(x2*x21 + x20*x16) - x8*uq4)) + x4*x18 + (2*x3 - x6)*x1*x15) + n1*(v0*uq11 + x1*x18 + x19*uhat2 + x23*(-uq8*x11 + x22*(uq11 - uhat0*(x21*x17 + x5*x20) - x8*uq8)) + (-x3 + 2*x6)*x4*x15) + tau0*(-uhat3 + uq3);
        }
        else if (ib == 5) {
            const dstype uq0 = uq[0];
            const dstype v1 = v[1];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1;
            f[2] = -uhat2;
            f[3] = -uhat3 + v1*uhat0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void flux_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uq0, -1);
        const dstype x1 = x0*uq2;
        const dstype x2 = uq10 - x1*uq8;
        const dstype x3 = x0*x2;
        const dstype x4 = x0*uq1;
        const dstype x5 = uq5 - x4*uq4;
        const dstype x6 = x0*x5;
        const dstype x7 = -x3 + 2*x6;
        const dstype x8 = Kokkos::pow(uq1, 2);
        const dstype x9 = Kokkos::pow(uq0, -3);
        const dstype x10 = x8*x9;
        const dstype x11 = Kokkos::pow(uq2, 2);
        const dstype x12 = x9*x11;
        const dstype x13 = 0.5*(-2*x10 - 2*x12);
        const dstype x14 = Kokkos::pow(uq0, -2);
        const dstype x15 = x14*x11;
        const dstype x16 = x8*x14;
        const dstype x17 = -0.5*x15 - 0.5*x16;
        const dstype x18 = x17 - uq0*x13;
        const dstype x19 = 0.5*(x15 + x16);
        const dstype x20 = uq3 - uq0*x19;
        const dstype x21 = Kokkos::pow(x20, 2);
        const dstype x22 = Kokkos::pow(mu3, 6);
        const dstype x23 = -1.0 + mu0;
        const dstype x24 = x22*Kokkos::pow(x23, 3)*Kokkos::pow(mu0, 3);
        const dstype x25 = x24*x21;
        const dstype x26 = x9*x25;
        const dstype x27 = Kokkos::pow(uq0, -4);
        const dstype x28 = x24*Kokkos::pow(x20, 3);
        const dstype x29 = Kokkos::sqrt(x9*x28);
        const dstype x30 = Kokkos::pow(mu1, -1);
        const dstype x31 = 110.4 + mu9;
        const dstype x32 = x0*x23;
        const dstype x33 = x32*x20;
        const dstype x34 = 1.0*mu0;
        const dstype x35 = Kokkos::pow(mu3, 2)*mu9;
        const dstype x36 = x34*x35;
        const dstype x37 = 110.4 + x33*x36;
        const dstype x38 = x30*x31/x37;
        const dstype x39 = x38/x29;
        const dstype x40 = (3*x26*x18 - 3*x28*x27)*x39;
        const dstype x41 = 0.333333333333333*x40;
        const dstype x42 = x7*x41;
        const dstype x43 = x23*x20;
        const dstype x44 = x43*x14;
        const dstype x45 = x32*x18;
        const dstype x46 = x30*x31*x29/Kokkos::pow(x37, 2);
        const dstype x47 = (-x44*x36 + x45*x36)*x46;
        const dstype x48 = 0.666666666666667*x47;
        const dstype x49 = x7*x48;
        const dstype x50 = x23*x18;
        const dstype x51 = x5*x14;
        const dstype x52 = x9*uq4;
        const dstype x53 = uq1*x52;
        const dstype x54 = x2*x14;
        const dstype x55 = x9*uq8;
        const dstype x56 = uq2*x55;
        const dstype x57 = x54 - x56;
        const dstype x58 = x38*x29;
        const dstype x59 = 0.666666666666667*x58;
        const dstype x60 = x59*(-2*x51 + 2*x53 + x57);
        const dstype x61 = uq6 - x1*uq4;
        const dstype x62 = uq9 - x4*uq8;
        const dstype x63 = x0*x61 + x0*x62;
        const dstype x64 = 0.5*x40;
        const dstype x65 = x63*x64;
        const dstype x66 = x62*x14;
        const dstype x67 = uq1*x55;
        const dstype x68 = x61*x14;
        const dstype x69 = uq2*x52;
        const dstype x70 = 1.0*x58;
        const dstype x71 = (-x66 + x67 - x68 + x69)*x70;
        const dstype x72 = uq2*x14;
        const dstype x73 = uq1*x72;
        const dstype x74 = 1.0*x63*x47;
        const dstype x75 = x65 + x71 - x73 - x74;
        const dstype x76 = uq2*x68;
        const dstype x77 = uq1*x51;
        const dstype x78 = x23*(uq7 - uq4*x19 - (x76 + x77)*uq0);
        const dstype x79 = uq0*x78 - uq4*x43;
        const dstype x80 = x9*x58;
        const dstype x81 = Kokkos::pow(x23, -1);
        const dstype x82 = Kokkos::pow(mu2, -1);
        const dstype x83 = x82*mu0;
        const dstype x84 = x81*x83;
        const dstype x85 = 2.0*x80*x84;
        const dstype x86 = x82*x79;
        const dstype x87 = x81*x47*x34*x14;
        const dstype x88 = x84*x14;
        const dstype x89 = x88*x64;
        const dstype x90 = x70*x72;
        const dstype x91 = 2*x9;
        const dstype x92 = uq1*x91;
        const dstype x93 = uq2*x91;
        const dstype x94 = uq4*x27;
        const dstype x95 = uq0*x23;
        const dstype x96 = x88*x70;
        const dstype x97 = -x44 + x45 - uq3*x14;
        const dstype x98 = uq1*x14;
        const dstype x99 = x59*x98;
        const dstype x100 = 2*x3 - x6;
        const dstype x101 = x41*x100;
        const dstype x102 = x48*x100;
        const dstype x103 = x51 - x53;
        const dstype x104 = x59*(x103 - 2*x54 + 2*x56);
        const dstype x105 = uq2*x54;
        const dstype x106 = uq1*x66;
        const dstype x107 = x23*(uq11 - uq8*x19 - (x105 + x106)*uq0);
        const dstype x108 = uq0*x107 - uq8*x43;
        const dstype x109 = x82*x108;
        const dstype x110 = x70*x98;
        const dstype x111 = uq8*x27;
        const dstype x112 = x72*x59;
        const dstype x113 = 1.0*x32;
        const dstype x114 = uq1*x113;
        const dstype x115 = -x114;
        const dstype x116 = uq1*x27;
        const dstype x117 = x39*x25;
        const dstype x118 = 1.0*x117;
        const dstype x119 = x7*x118;
        const dstype x120 = x119*x116;
        const dstype x121 = 1.33333333333333*x58;
        const dstype x122 = uq4*x14;
        const dstype x123 = x46*x35;
        const dstype x124 = mu0*x123;
        const dstype x125 = 0.666666666666667*x124;
        const dstype x126 = x23*x125;
        const dstype x127 = x7*x126;
        const dstype x128 = x98*x127;
        const dstype x129 = 1.5*x63;
        const dstype x130 = x117*x129;
        const dstype x131 = x116*x130;
        const dstype x132 = 1.0*uq8;
        const dstype x133 = x58*x14;
        const dstype x134 = x133*x132;
        const dstype x135 = 1.0*x23;
        const dstype x136 = x63*x124;
        const dstype x137 = x135*x136;
        const dstype x138 = x98*x137;
        const dstype x139 = x1 - x131 - x134 + x138;
        const dstype x140 = Kokkos::pow(uq0, -5);
        const dstype x141 = x119*x140;
        const dstype x142 = 1.5*x39*x22*Kokkos::pow(x23, 2)*x21*Kokkos::pow(mu0, 4);
        const dstype x143 = x142/Kokkos::pow(uq0, 6);
        const dstype x144 = x86*x143;
        const dstype x145 = 1.0*Kokkos::pow(mu0, 2);
        const dstype x146 = x123*x145;
        const dstype x147 = x116*x146;
        const dstype x148 = x0*x59;
        const dstype x149 = 1.0*uq4;
        const dstype x150 = uq2*uq1;
        const dstype x151 = x130*x140;
        const dstype x152 = x9*x123;
        const dstype x153 = mu0*x150*x152;
        const dstype x154 = x33 + x0*uq3 - x150*x151 + x63*x135*x153;
        const dstype x155 = x100*x126;
        const dstype x156 = x100*x118;
        const dstype x157 = x109*x143;
        const dstype x158 = x140*x156;
        const dstype x159 = 0.666666666666667*x23*x153;
        const dstype x160 = x0*x70;
        const dstype x161 = x63*x160 - x73*x135;
        const dstype x162 = uq2*x113;
        const dstype x163 = -x162;
        const dstype x164 = uq2*x27;
        const dstype x165 = uq8*x14;
        const dstype x166 = x164*x130;
        const dstype x167 = x72*x137;
        const dstype x168 = x133*x149;
        const dstype x169 = -x166 + x167 - x168 + x4;
        const dstype x170 = x164*x146;
        const dstype x171 = x72*x155;
        const dstype x172 = x164*x156;
        const dstype x173 = x39*x26;
        const dstype x174 = 1.0*x173;
        const dstype x175 = x32*x125;
        const dstype x176 = -x113*x136 + x129*x173;
        const dstype x177 = x0 + x32;
        const dstype x178 = x145*x152;
        const dstype x179 = x140*x142;
        const dstype x180 = x98*x121;
        const dstype x181 = -x90;
        const dstype x182 = x96*(-x43 + x95*(x17 - (-x10 - x12)*uq0));
        const dstype x183 = -0.333333333333333*x80*x150;
        const dstype x184 = v0 + x0*x121;
        const dstype x185 = -x83*x110;
        const dstype x186 = -x148;
        const dstype x187 = v0 + x160;
        const dstype x188 = -x83*x90;
        const dstype x189 = v0 + x83*x160;
        const dstype x190 = -x110;
        const dstype x191 = x72*x121;

        f[0] = 0;
        f[1] = -x16 + x42 - x49 + x50 + x60;
        f[2] = x75;
        f[3] = uq1*x97 + x1*x65 + x1*x71 - x1*x74 + x4*x42 - x4*x49 + x4*x60 - x63*x90 - x7*x99 - x85*x79 - x86*x87 + x89*x79 + x96*(x78 - uq4*x50 + x95*(-x76 - x77 - uq4*x13 - (-x5*x92 - x61*x93 + x8*x94 + x94*x11)*uq0));
        f[4] = 0;
        f[5] = x75;
        f[6] = x101 - x102 + x104 - x15 + x50;
        f[7] = uq2*x97 + x1*x101 - x1*x102 + x1*x104 - x100*x112 + x4*x65 + x4*x71 - x4*x74 - x63*x110 - x85*x108 - x87*x109 + x89*x108 + x96*(x107 - uq8*x50 + x95*(-x105 - x106 - uq0*(x11*x111 - x2*x93 - x62*x92 + x8*x111) - uq8*x13));
        f[8] = 1;
        f[9] = x115 - x120 + x128 + 2*x4 - x122*x121;
        f[10] = x139;
        f[11] = x154 - uq1*x144 + x10*x127 - x16*x135 - x53*x121 + x7*x148 - x70*x56 - x8*x141 + x86*x147 + x96*(uq4*x114 + x95*(-uq0*x103 - x98*x149));
        f[12] = 0;
        f[13] = x139;
        f[14] = x115 - x116*x156 + x59*x122 + x98*x155;
        f[15] = x161 - uq1*x157 + x10*x137 + x100*x159 + x109*x147 - x150*x158 + x69*x59 - x70*x67 - x8*x151 + x96*(uq8*x114 + x95*(-x98*x132 - (x66 - x67)*uq0));
        f[16] = 0;
        f[17] = x163 - x119*x164 + x59*x165 + x72*x127;
        f[18] = x169;
        f[19] = x161 - uq2*x144 - x11*x151 + x12*x137 - x141*x150 + x67*x59 + x7*x159 - x70*x69 + x86*x170 + x96*(uq4*x162 + x95*(-x72*x149 - (x68 - x69)*uq0));
        f[20] = 1;
        f[21] = x169;
        f[22] = 2*x1 + x163 + x171 - x172 - x121*x165;
        f[23] = x154 - uq2*x157 + x100*x148 + x109*x170 - x11*x158 + x12*x155 - x15*x135 - x56*x121 - x70*x53 + x96*(uq8*x162 + x95*(-uq0*x57 - x72*x132));
        f[24] = 0;
        f[25] = x23 + x7*x174 - x7*x175;
        f[26] = x176;
        f[27] = x120 - x128 + x166 - x167 + uq1*x177 - x83*x168 - x86*x178 + x86*x179;
        f[28] = 0;
        f[29] = x176;
        f[30] = x23 + x100*x174 - x100*x175;
        f[31] = x131 - x138 - x171 + x172 + uq2*x177 - x109*x178 + x109*x179 - x83*x134;
        f[32] = v0;
        f[33] = -x180;
        f[34] = x181;
        f[35] = x182 - x10*x121 - x70*x12;
        f[36] = 0;
        f[37] = x181;
        f[38] = x99;
        f[39] = x183;
        f[40] = 0;
        f[41] = x184;
        f[42] = 0;
        f[43] = x180 + x185;
        f[44] = 0;
        f[45] = 0;
        f[46] = x186;
        f[47] = -x112;
        f[48] = 0;
        f[49] = 0;
        f[50] = x187;
        f[51] = x188 + x90;
        f[52] = 0;
        f[53] = x160;
        f[54] = 0;
        f[55] = x110;
        f[56] = 0;
        f[57] = 0;
        f[58] = 0;
        f[59] = x189;
        f[60] = 0;
        f[61] = 0;
        f[62] = 0;
        f[63] = 0;
        f[64] = 0;
        f[65] = x112;
        f[66] = x190;
        f[67] = x183;
        f[68] = v0;
        f[69] = x190;
        f[70] = -x191;
        f[71] = x182 - x12*x121 - x70*x10;
        f[72] = 0;
        f[73] = 0;
        f[74] = x160;
        f[75] = x90;
        f[76] = 0;
        f[77] = x187;
        f[78] = 0;
        f[79] = x110 + x185;
        f[80] = 0;
        f[81] = x186;
        f[82] = 0;
        f[83] = -x99;
        f[84] = 0;
        f[85] = 0;
        f[86] = x184;
        f[87] = x188 + x191;
        f[88] = 0;
        f[89] = 0;
        f[90] = 0;
        f[91] = 0;
        f[92] = 0;
        f[93] = 0;
        f[94] = 0;
        f[95] = x189;
    }

    KOKKOS_INLINE_FUNCTION static
    void source_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
        f[4] = 0;
        f[5] = 0;
        f[6] = 0;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = 0;
        f[11] = 0;
        f[12] = 0;
        f[13] = 0;
        f[14] = 0;
        f[15] = 0;
        f[16] = 0;
        f[17] = 0;
        f[18] = 0;
        f[19] = 0;
        f[20] = 0;
        f[21] = 0;
        f[22] = 0;
        f[23] = 0;
        f[24] = 0;
        f[25] = 0;
        f[26] = 0;
        f[27] = 0;
        f[28] = 0;
        f[29] = 0;
        f[30] = 0;
        f[31] = 0;
        f[32] = 0;
        f[33] = 0;
        f[34] = 0;
        f[35] = 0;
        f[36] = 0;
        f[37] = 0;
        f[38] = 0;
        f[39] = 0;
        f[40] = 0;
        f[41] = 0;
        f[42] = 0;
        f[43] = 0;
        f[44] = 0;
        f[45] = 0;
        f[46] = 0;
        f[47] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 1;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 3) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 4) {
            const dstype v0 = v[0];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype mu0 = mu[0];
            const dstype mu1 = mu[1];
            const dstype mu2 = mu[2];
            const dstype mu3 = mu[3];
            const dstype mu9 = mu[9];

            const dstype x0 = Kokkos::pow(uhat0, -3);
            const dstype x1 = Kokkos::pow(uhat1, 2);
            const dstype x2 = x0*x1;
            const dstype x3 = Kokkos::pow(uhat0, -2);
            const dstype x4 = Kokkos::pow(uhat2, 2);
            const dstype x5 = x4*x3;
            const dstype x6 = x1*x3;
            const dstype x7 = uhat3 - 0.5*(x5 + x6)*uhat0;
            const dstype x8 = -1.0 + mu0;
            const dstype x9 = x8*x7;
            const dstype x10 = 1.0*mu0;
            const dstype x11 = x10/uhat0;
            const dstype x12 = (110.4 + mu9)*Kokkos::sqrt(x0*Kokkos::pow(x8, 3)*Kokkos::pow(x7, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3))/(mu1*(110.4 + x9*x11*Kokkos::pow(mu3, 2)*mu9));
            const dstype x13 = 1.33333333333333*x12;
            const dstype x14 = x0*x4;
            const dstype x15 = 1.0*x12;
            const dstype x16 = x3*x12;
            const dstype x17 = Kokkos::pow(mu2, -1);
            const dstype x18 = x10*x17;
            const dstype x19 = x18*x16*(-x9 + x8*uhat0*(-0.5*x5 - 0.5*x6 - (-x14 - x2)*uhat0))/x8;
            const dstype x20 = 0.333333333333333*x0*x12*uhat2*uhat1;
            const dstype x21 = x16*uhat1;
            const dstype x22 = -x21*x18;
            const dstype x23 = x16*uhat2;
            const dstype x24 = 1.0*x23;
            const dstype x25 = -x23*x18;
            const dstype x26 = 1.0*x21;
            const dstype x27 = v0 + x12*x11*x17;

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = tau0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = n0*(x19 - x15*x14 - x2*x13) - n1*x20;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = n0*(1.33333333333333*x21 + x22) - 0.666666666666667*n1*x23;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = n1*x26 + (x24 + x25)*n0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = n0*x27;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = -n0*x20 + n1*(x19 - x14*x13 - x2*x15);
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = n0*x24 + (x22 + x26)*n1;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = -0.666666666666667*n0*x21 + n1*(1.33333333333333*x23 + x25);
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = n1*x27;
        }
        else if (ib == 5) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 2) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 3) {
            const dstype mu8 = mu[8];
            const dstype mu9 = mu[9];
            const dstype mu10 = mu[10];

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = mu8*mu10/mu9;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 4) {
            const dstype uq4 = uq[4];
            const dstype uq5 = uq[5];
            const dstype uq6 = uq[6];
            const dstype uq7 = uq[7];
            const dstype uq8 = uq[8];
            const dstype uq9 = uq[9];
            const dstype uq10 = uq[10];
            const dstype uq11 = uq[11];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype mu0 = mu[0];
            const dstype mu1 = mu[1];
            const dstype mu2 = mu[2];
            const dstype mu3 = mu[3];
            const dstype mu9 = mu[9];

            const dstype x0 = Kokkos::pow(uhat0, -2);
            const dstype x1 = Kokkos::pow(uhat2, 2);
            const dstype x2 = x0*x1;
            const dstype x3 = Kokkos::pow(uhat1, 2);
            const dstype x4 = x0*x3;
            const dstype x5 = 0.5*(x2 + x4);
            const dstype x6 = uhat3 - x5*uhat0;
            const dstype x7 = Kokkos::pow(uhat0, -1);
            const dstype x8 = -1.0 + mu0;
            const dstype x9 = x8*x7;
            const dstype x10 = x6*x9;
            const dstype x11 = Kokkos::pow(mu3, 2);
            const dstype x12 = 1.0*x11*mu9;
            const dstype x13 = x12*mu0;
            const dstype x14 = 110.4 + x13*x10;
            const dstype x15 = Kokkos::pow(x14, -1);
            const dstype x16 = Kokkos::pow(mu1, -1);
            const dstype x17 = 110.4 + mu9;
            const dstype x18 = Kokkos::pow(uhat0, -3);
            const dstype x19 = Kokkos::pow(mu3, 6);
            const dstype x20 = Kokkos::pow(x8, 3)*x19*Kokkos::pow(mu0, 3);
            const dstype x21 = Kokkos::pow(x6, 3)*x20;
            const dstype x22 = Kokkos::sqrt(x21*x18);
            const dstype x23 = x22*x17*x16;
            const dstype x24 = x23*x15;
            const dstype x25 = x0*x24;
            const dstype x26 = x7*uhat2;
            const dstype x27 = uq10 - uq8*x26;
            const dstype x28 = x7*x27;
            const dstype x29 = x7*uhat1;
            const dstype x30 = uq5 - uq4*x29;
            const dstype x31 = x7*x30;
            const dstype x32 = -x28 + 2*x31;
            const dstype x33 = 0.666666666666667*x32;
            const dstype x34 = x33*uhat1;
            const dstype x35 = x6*x8;
            const dstype x36 = x0*x35;
            const dstype x37 = 2*x18;
            const dstype x38 = 0.5*(-x1*x37 - x3*x37);
            const dstype x39 = -0.5*x2 - 0.5*x4 - x38*uhat0;
            const dstype x40 = x9*x39;
            const dstype x41 = x23/Kokkos::pow(x14, 2);
            const dstype x42 = (-x36*x13 + x40*x13)*x41;
            const dstype x43 = x42*x29;
            const dstype x44 = Kokkos::pow(x6, 2);
            const dstype x45 = x44*x20;
            const dstype x46 = Kokkos::pow(uhat0, -4);
            const dstype x47 = x15*x17*x16/x22;
            const dstype x48 = x47*(-3*x46*x21 + 3*x45*x39*x18);
            const dstype x49 = x48*x29;
            const dstype x50 = 1.0*x0;
            const dstype x51 = x50*uhat2;
            const dstype x52 = uq6 - uq4*x26;
            const dstype x53 = uq9 - uq8*x29;
            const dstype x54 = x7*x52 + x7*x53;
            const dstype x55 = x54*x24;
            const dstype x56 = x0*x52;
            const dstype x57 = x56*uhat2;
            const dstype x58 = x0*x30;
            const dstype x59 = x58*uhat1;
            const dstype x60 = x8*(uq7 - x5*uq4 - (x57 + x59)*uhat0);
            const dstype x61 = x37*uhat1;
            const dstype x62 = x37*uhat2;
            const dstype x63 = uq4*x46;
            const dstype x64 = x8*uhat0;
            const dstype x65 = x8*x39;
            const dstype x66 = Kokkos::pow(x8, -1);
            const dstype x67 = Kokkos::pow(mu2, -1);
            const dstype x68 = x67*mu0;
            const dstype x69 = x68*x24;
            const dstype x70 = x69*x50;
            const dstype x71 = x70*x66;
            const dstype x72 = 1.0*x54;
            const dstype x73 = x42*x26;
            const dstype x74 = -uq4*x35 + x60*uhat0;
            const dstype x75 = x74*x66;
            const dstype x76 = x75*x68;
            const dstype x77 = x50*x42;
            const dstype x78 = x24*x26;
            const dstype x79 = x0*x53;
            const dstype x80 = uq8*x18;
            const dstype x81 = x80*uhat1;
            const dstype x82 = uq4*x18;
            const dstype x83 = x82*uhat2;
            const dstype x84 = 1.0*(-x56 - x79 + x81 + x83);
            const dstype x85 = 2.0*x69*x18;
            const dstype x86 = -x36 + x40 - x0*uhat3;
            const dstype x87 = x0*x27;
            const dstype x88 = x80*uhat2;
            const dstype x89 = x87 - x88;
            const dstype x90 = x24*x29;
            const dstype x91 = 0.5*x54;
            const dstype x92 = x48*x26;
            const dstype x93 = 0.5*x0*x48;
            const dstype x94 = 2*x28 - x31;
            const dstype x95 = 0.666666666666667*x94;
            const dstype x96 = x50*uhat1;
            const dstype x97 = x87*uhat2;
            const dstype x98 = x79*uhat1;
            const dstype x99 = x8*(uq11 - x5*uq8 - (x97 + x98)*uhat0);
            const dstype x100 = -uq8*x35 + x99*uhat0;
            const dstype x101 = x66*x100;
            const dstype x102 = x95*uhat2;
            const dstype x103 = x82*uhat1;
            const dstype x104 = -x103 + x58;
            const dstype x105 = x68*x101;
            const dstype x106 = uq8*x46;
            const dstype x107 = x7*x24;
            const dstype x108 = x41*x18;
            const dstype x109 = x3*x108;
            const dstype x110 = x11*mu9*mu0;
            const dstype x111 = x8*x110;
            const dstype x112 = x47/Kokkos::pow(uhat0, 5);
            const dstype x113 = 1.0*x45;
            const dstype x114 = x32*x113;
            const dstype x115 = x112*x114;
            const dstype x116 = 1.0*x24;
            const dstype x117 = 1.33333333333333*x24;
            const dstype x118 = 1.0*x8;
            const dstype x119 = x74*x67;
            const dstype x120 = x12*Kokkos::pow(mu0, 2);
            const dstype x121 = x41*x120;
            const dstype x122 = x46*uhat1;
            const dstype x123 = x122*x121;
            const dstype x124 = 1.0*x9;
            const dstype x125 = uq4*x124;
            const dstype x126 = Kokkos::pow(x8, 2)*x44*x19*Kokkos::pow(mu0, 4);
            const dstype x127 = 1.5*x47*x126/Kokkos::pow(uhat0, 6);
            const dstype x128 = x127*uhat1;
            const dstype x129 = 1.5*x112;
            const dstype x130 = x54*x45;
            const dstype x131 = x129*x130;
            const dstype x132 = uhat2*uhat1;
            const dstype x133 = x54*x110;
            const dstype x134 = x118*x133;
            const dstype x135 = x10 - x131*x132 + x7*uhat3 + x108*x134*x132;
            const dstype x136 = x67*x100;
            const dstype x137 = uq8*x124;
            const dstype x138 = x94*x113;
            const dstype x139 = x102*x111;
            const dstype x140 = 0.666666666666667*x24;
            const dstype x141 = x8*x51;
            const dstype x142 = -x141*uhat1 + x72*x107;
            const dstype x143 = x34*x111;
            const dstype x144 = x1*x108;
            const dstype x145 = x1*x112;
            const dstype x146 = 1.5*x130;
            const dstype x147 = x46*uhat2;
            const dstype x148 = x121*x147;
            const dstype x149 = x127*uhat2;
            const dstype x150 = x7 + x9;
            const dstype x151 = x41*x133;
            const dstype x152 = x47*x122;
            const dstype x153 = x47*x147;
            const dstype x154 = x108*x120;
            const dstype x155 = x0*x41;
            const dstype x156 = x126*x129;

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = n0*(-x34*x25 - x43*x33 + 0.333333333333333*x49*x32 - x51*x55 + x71*(x60 - uq4*x65 + x64*(-x57 - x59 - uq4*x38 - (x1*x63 + x3*x63 - x61*x30 - x62*x52)*uhat0)) - x73*x72 + x76*x93 - x77*x76 + x84*x78 - x85*x75 + x86*uhat1 + 0.666666666666667*x90*(-2*x58 + x89 + uq4*x61) + x92*x91) + n1*(-x25*x102 - x55*x96 + x71*(x99 - uq8*x65 + x64*(-x97 - x98 - uq8*x38 - (x1*x106 + x3*x106 - x61*x53 - x62*x27)*uhat0)) - x72*x43 - x73*x95 - x77*x105 + 0.666666666666667*x78*(x104 - 2*x87 + uq8*x62) + x84*x90 - x85*x101 + x86*uhat2 + x91*x49 + 0.333333333333333*x92*x94 + x93*x105);
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = n0*(x135 - x103*x117 + x119*x123 - x119*x128 - x3*x115 + x33*x107 - x4*x118 + x71*(x125*uhat1 + x64*(-uq4*x96 - x104*uhat0)) - x88*x116 + x33*x109*x111) + n1*(x142 + x109*x134 + x123*x136 - x128*x136 - x3*x131 + x71*(x137*uhat1 + x64*(-uq8*x96 - (x79 - x81)*uhat0)) - x81*x116 + x83*x140 + x108*x139*uhat1 - x112*x132*x138);
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = n0*(x142 - x115*x132 + x119*x148 - x119*x149 + x134*x144 - x146*x145 + x71*(x125*uhat2 + x64*(-uq4*x51 - (x56 - x83)*uhat0)) + x81*x140 - x83*x116 + x108*x143*uhat2) + n1*(x135 - x103*x116 + x136*x148 - x136*x149 - x138*x145 - x2*x118 + x71*(x137*uhat2 + x64*(-uq8*x51 - x89*uhat0)) - x88*x117 + x95*x107 + x95*x111*x144);
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -tau0 + n0*(-uq4*x70 + x114*x152 - x119*x154 + x119*x156 - x141*x151 - x143*x155 + x146*x153 + x150*uhat1) + n1*(-uq8*x70 - x136*x154 + x136*x156 + x138*x153 - x139*x155 + x146*x152 + x150*uhat2 - x8*x96*x151);
        }
        else if (ib == 5) {
            const dstype v1 = v[1];

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = v1;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
    }

};
