function dest = exporttext2code(pde, mesh, dest)
%EXPORTTEXT2CODE Export a self-contained Text2Code application package.
%
%   dest = exporttext2code(pde, mesh, dest) writes the files needed by the
%   Exasim text2code executable to reconstruct the application without the
%   original MATLAB script:
%
%     pdemodel.txt
%     pdeapp.txt
%     grid.bin
%     xdg.bin, udg.bin, vdg.bin, wdg.bin when present in mesh
%
%   This differs from exportapp: exportapp packages generated kernels and a
%   C++ driver ready to build, while exporttext2code packages the higher-level
%   Text2Code inputs used to regenerate those kernels.

if nargin < 3 || isempty(dest)
    pde0 = pde;
    if iscell(pde0)
        pde0 = pde0{1};
    end
    if isfield(pde0, 'exporttext2code') && ~isempty(pde0.exporttext2code)
        dest = pde0.exporttext2code;
    elseif isfield(pde0, 'exportt2c') && ~isempty(pde0.exportt2c)
        dest = pde0.exportt2c;
    else
        error("exporttext2code: no destination (pass dest or set pde.exporttext2code).");
    end
end

dest = string(exporttext2code_abspath(dest));
if exist(char(dest), 'dir') == 0
    mkdir(char(dest));
end

fprintf("Export Exasim Text2Code package to %s ...\n", dest);

if iscell(pde)
    exporttext2code_coupled(pde, mesh, dest);
else
    exporttext2code_single(pde, mesh, dest, "", 1, 0);
    write_text2code_readme(dest, false, 1);
end

fprintf("Exported Text2Code package: %s\n", dest);
end

function exporttext2code_coupled(pdes, meshes, dest)
if ~iscell(meshes)
    error("exporttext2code: coupled export requires mesh to be a cell array.");
end
nmodels = numel(pdes);
if nmodels ~= numel(meshes)
    error("exporttext2code: pde and mesh cell arrays must have the same length.");
end
if nmodels < 2
    error("exporttext2code: coupled export requires at least two models.");
end

modelids = zeros(1, nmodels);
for m = 1:nmodels
    suffix = num2str(m);
    pdeout = exporttext2code_single(pdes{m}, meshes{m}, dest, suffix, nmodels, m);
    modelids(m) = pdeout.builtinmodelID;
end
write_coupled_runtime(dest, nmodels, modelids);
write_text2code_readme(dest, true, nmodels);
end

function pdeout = exporttext2code_single(pde, mesh, dest, suffix, nmodels, modelslot)
% writeinputfile writes pdeapp.txt in the current directory. The exporter
% writes binary files explicitly so coupled models get deterministic names.
pdeout = pde;
pdeout = exporttext2code_infer_dimensions(pdeout, mesh);
if (~isfield(pdeout, 'model') || isempty(pdeout.model)) && isfield(pdeout, 'pdemodel')
    pdeout.model = pdeout.pdemodel;
end

if modelslot > 0
    pdeout.builtinmodelID = exporttext2code_modelid(pdeout, modelslot);
elseif ~isfield(pdeout, 'builtinmodelID') || isempty(pdeout.builtinmodelID)
    pdeout.builtinmodelID = 0;
end
pdeout.frontendgenerated = 0;

pdemodelname = "pdemodel" + suffix;
pdeappname = "pdeapp" + suffix + ".txt";
gridname = "grid" + suffix + ".bin";
materialdatabasename = "materialdatabase" + suffix + ".bin";

genpdemodel(pdeout, dest + "/" + pdemodelname + ".txt");
pdeout.modelfile = pdemodelname;
if isfield(pdeout, "physicsparamsweep") && ~isempty(pdeout.physicsparamsweep)
    pdeout.physicsparamcases = exporttext2code_sweepcases(pdeout.physicsparamsweep, numel(pdeout.physicsparam));
end
for key = ["meshfile", "xdgfile", "udgfile", "vdgfile", "wdgfile"]
    if isfield(pdeout, key)
        pdeout = rmfield(pdeout, key);
    end
end
pdeout.meshfile = gridname;
writebin(char(dest + "/" + gridname), [size(mesh.p) size(mesh.t) mesh.p(:)' mesh.t(:)']);

if isfield(mesh, 'dgnodes')
    pdeout.xdgfile = "xdg" + suffix + ".bin";
    writebin(char(dest + "/" + pdeout.xdgfile), [size(mesh.dgnodes) mesh.dgnodes(:)']);
end
if isfield(mesh, 'udg')
    pdeout.udgfile = "udg" + suffix + ".bin";
    writebin(char(dest + "/" + pdeout.udgfile), [size(mesh.udg) mesh.udg(:)']);
end
if isfield(mesh, 'vdg')
    pdeout.vdgfile = "vdg" + suffix + ".bin";
    writebin(char(dest + "/" + pdeout.vdgfile), [size(mesh.vdg) mesh.vdg(:)']);
end
if isfield(mesh, 'wdg')
    pdeout.wdgfile = "wdg" + suffix + ".bin";
    writebin(char(dest + "/" + pdeout.wdgfile), [size(mesh.wdg) mesh.wdg(:)']);
end
if isfield(pdeout, 'materialdatabase') && ~isempty(strtrim(char(pdeout.materialdatabase)))
    process_materialdatabase(pdeout, dest, materialdatabasename);
    pdeout.materialdatabase = materialdatabasename;
end

olddir = pwd();
cleanup = onCleanup(@() cd(olddir));
cd(char(dest));
writeinputfile(pdeappname, pdeout, mesh);
clear cleanup;
cd(olddir);
end

function id = exporttext2code_modelid(pde, modelslot)
if isfield(pde, 'builtinmodelID') && ~isempty(pde.builtinmodelID) && pde.builtinmodelID > 0
    id = pde.builtinmodelID;
elseif isfield(pde, 'modelid') && ~isempty(pde.modelid) && pde.modelid >= 0
    id = pde.modelid;
else
    % External text2code coupled apps use one provider ID per model slot.
    id = 100 + modelslot - 1;
end
end

function pde = exporttext2code_infer_dimensions(pde, mesh)
if isfield(mesh, 'p') && ~isempty(mesh.p)
    nd = size(mesh.p, 1);
    pde.nd = nd;
    pde.ncx = nd;
elseif isfield(pde, 'nd')
    nd = pde.nd;
else
    nd = 1;
end
pde = exporttext2code_infer_model_dimensions(pde);
model = "ModelD";
if isfield(pde, 'model') && ~isempty(pde.model)
    model = string(pde.model);
elseif isfield(pde, 'pdemodel') && ~isempty(pde.pdemodel)
    model = string(pde.pdemodel);
end
if lower(model) == "modelc"
    nc = pde.ncu;
else
    nc = pde.ncu * (nd + 1);
end
if ~isfield(pde, 'nc') || isempty(pde.nc) || pde.nc < nc
    pde.nc = nc;
end
pde.ncq = max(pde.nc - pde.ncu, 0);
if isfield(mesh, 'vdg') && ~isempty(mesh.vdg)
    pde.nco = size(mesh.vdg, 2);
end
if isfield(mesh, 'wdg') && ~isempty(mesh.wdg)
    pde.ncw = size(mesh.wdg, 2);
end
end

function pde = exporttext2code_infer_model_dimensions(pde)
if ~isfield(pde, 'modelfile') || isempty(pde.modelfile)
    if isfield(pde, 'model') && ~isempty(pde.model)
        pde.modelfile = pde.model;
    else
        pde.modelfile = "pdemodel";
    end
end

pdemodelfun = str2func(pde.modelfile);
pdem = pdemodelfun();

nuinf = numel(pde.externalparam);
nparam = numel(pde.physicsparam);
xdgsym = sym('xdg', [pde.ncx 1]);
uinfsym = sym('uinf', [nuinf 1]);
paramsym = sym('param', [nparam 1]);

if isfield(pdem, 'initu')
    udgsym = pdem.initu(xdgsym, paramsym, uinfsym);
    pde.ncu = numel(udgsym(:));
elseif ~isfield(pde, 'ncu') || isempty(pde.ncu)
    pde.ncu = 1;
end

if isfield(pdem, 'initv')
    odgsym = pdem.initv(xdgsym, paramsym, uinfsym);
    pde.nco = numel(odgsym(:));
elseif ~isfield(pde, 'nco') || isempty(pde.nco)
    pde.nco = 0;
end

if isfield(pdem, 'initw')
    wdgsym = pdem.initw(xdgsym, paramsym, uinfsym);
    pde.ncw = numel(wdgsym(:));
elseif ~isfield(pde, 'ncw') || isempty(pde.ncw)
    pde.ncw = 0;
end
end

function cases = exporttext2code_sweepcases(spec, nparam)
if isnumeric(spec)
    if isvector(spec) && nparam == 1
        cases = spec(:);
    else
        cases = spec;
    end
elseif iscell(spec)
    cases = zeros(numel(spec), nparam);
    for i = 1:numel(spec)
        v = spec{i};
        if numel(v) ~= nparam
            error("physicsparamsweep case %d has %d parameters; expected %d.", i, numel(v), nparam);
        end
        cases(i,:) = reshape(v, 1, []);
    end
elseif isstruct(spec)
    if isfield(spec, 'samples')
        cases = exporttext2code_sweepcases(spec.samples, nparam);
    elseif isfield(spec, 'values')
        cases = exporttext2code_sweepcases(spec.values, nparam);
    elseif isfield(spec, 'grid')
        if ~iscell(spec.grid) || numel(spec.grid) ~= nparam
            error("physicsparamsweep.grid must be a cell array with one value vector per physics parameter.");
        end
        grids = cellfun(@(v) v(:), spec.grid, 'UniformOutput', false);
        [meshgrids{1:nparam}] = ndgrid(grids{:});
        cases = zeros(numel(meshgrids{1}), nparam);
        for j = 1:nparam
            cases(:,j) = meshgrids{j}(:);
        end
    else
        error("physicsparamsweep struct must contain samples, values, or grid.");
    end
else
    error("physicsparamsweep must be numeric, a cell array, or a struct.");
end
if size(cases,2) ~= nparam
    error("Each physicsparamsweep row must contain %d physics parameters.", nparam);
end
if any(~isfinite(cases(:)))
    error("physicsparamsweep cases must contain finite numeric values.");
end
end

function p = exporttext2code_abspath(p)
p = char(string(p));
if ~isempty(p) && (p(1) == filesep || contains(p, ':\'))
    % Already absolute on Unix or Windows.
else
    p = fullfile(pwd(), p);
end
end

function write_coupled_runtime(dest, nmodels, modelids)
if nmodels ~= 2
    warning("exporttext2code: generated runtime currently supports Exasim's two-domain coupled solver; exported %d models.", nmodels);
end

idlist = join(string(modelids), " ");
pdeapps = strings(1, nmodels);
copylines = strings(0, 1);
copylines(end+1) = "set(_EXASIM_COUPLED_CODEGEN_INPUT_DIR ""${CMAKE_BINARY_DIR}/exasim_external_models/coupled_text2code_models/codegen_inputs"")";
copylines(end+1) = "file(MAKE_DIRECTORY ""${_EXASIM_COUPLED_CODEGEN_INPUT_DIR}"")";
for m = 1:nmodels
    pdeapps(m) = "${_EXASIM_COUPLED_CODEGEN_INPUT_DIR}/pdeapp" + num2str(m) + ".txt";
    pdeappvar = "_exasim_coupled_pdeapp_" + num2str(m);
    copylines(end+1) = "file(READ ""${CMAKE_CURRENT_SOURCE_DIR}/pdeapp" + num2str(m) + ".txt"" " + pdeappvar + ")"; %#ok<AGROW>
    copylines(end+1) = "file(WRITE ""${_EXASIM_COUPLED_CODEGEN_INPUT_DIR}/pdeapp" + num2str(m) + ".txt"" ""gendatain = 0;\n${" + pdeappvar + "}"")"; %#ok<AGROW>
    copylines(end+1) = "configure_file(""${CMAKE_CURRENT_SOURCE_DIR}/pdemodel" + num2str(m) + ".txt"" ""${_EXASIM_COUPLED_CODEGEN_INPUT_DIR}/pdemodel" + num2str(m) + ".txt"" COPYONLY)"; %#ok<AGROW>
end
copylines = copylines(:);
pdeapplist = join(pdeapps, newline + "           ");

cmake = [
"cmake_minimum_required(VERSION 3.16)"; ...
"project(exasim_text2code_coupled_problem CXX)"; ...
"set(CMAKE_CXX_STANDARD 20)"; ...
""; ...
"option(EXASIM_MPI ""MPI variant"" ON)"; ...
"if(EXASIM_MPI)"; ...
"  set(EXASIM_VARIANT cpumpi)"; ...
"  set(EXASIM_SOLVER_TARGET Exasim::cpumpilib)"; ...
"else()"; ...
"  set(EXASIM_VARIANT cpu)"; ...
"  set(EXASIM_SOLVER_TARGET Exasim::cpulib)"; ...
"endif()"; ...
"find_package(Exasim REQUIRED COMPONENTS ${EXASIM_VARIANT})"; ...
"find_package(Kokkos REQUIRED)"; ...
"if(EXASIM_MPI)"; ...
"  find_package(MPI REQUIRED)"; ...
"endif()"; ...
"set(EXASIM_TEXT2CODE_EXECUTABLE """" CACHE FILEPATH ""Override text2code executable used for coupled app codegen and runtime"")"; ...
"if(EXASIM_TEXT2CODE_EXECUTABLE)"; ...
"  set(Exasim_TEXT2CODE ""${EXASIM_TEXT2CODE_EXECUTABLE}"")"; ...
"endif()"; ...
""; ...
copylines; ...
""; ...
"exasim_add_external_builtin_model(TARGET coupled_text2code_models"; ...
"  IDS " + idlist; ...
"  PDEMODEL " + pdeapplist + ")"; ...
""; ...
"add_executable(exasimapp main.cpp)"; ...
"target_compile_definitions(exasimapp PRIVATE _BUILTINLIBRARY)"; ...
"target_compile_definitions(exasimapp PRIVATE EXASIM_TEXT2CODE_EXECUTABLE=""${Exasim_TEXT2CODE}"")"; ...
"if(EXASIM_MPI)"; ...
"  target_compile_definitions(exasimapp PRIVATE _MPI)"; ...
"endif()"; ...
"target_link_libraries(exasimapp PRIVATE"; ...
"  Exasim::headers ${EXASIM_SOLVER_TARGET} coupled_text2code_models Kokkos::kokkos)"; ...
"if(EXASIM_MPI)"; ...
"  target_link_libraries(exasimapp PRIVATE MPI::MPI_CXX)"; ...
"endif()"; ...
""];

maincpp = [
"// Generated by MATLAB exporttext2code for a coupled Text2Code application."; ...
"// Runtime syntax:"; ...
"//   mpirun -np <sum ranks> build/exasimapp pdeapp1.txt <ranks1> pdeapp2.txt <ranks2>"; ...
"#include <cstdlib>"; ...
"#include <filesystem>"; ...
"#include <iostream>"; ...
"#include <numeric>"; ...
"#include <string>"; ...
"#include <vector>"; ...
""; ...
"#include <exasim/ExasimSolverSetup.hpp>"; ...
""; ...
"namespace {"; ...
"std::string quote(const std::filesystem::path& p)"; ...
"{"; ...
"    return std::string(1, char(34)) + p.string() + std::string(1, char(34));"; ...
"}"; ...
""; ...
"int rank_world()"; ...
"{"; ...
"#ifdef HAVE_MPI"; ...
"    int r = 0;"; ...
"    MPI_Comm_rank(MPI_COMM_WORLD, &r);"; ...
"    return r;"; ...
"#else"; ...
"    return 0;"; ...
"#endif"; ...
"}"; ...
""; ...
"int size_world()"; ...
"{"; ...
"#ifdef HAVE_MPI"; ...
"    int n = 1;"; ...
"    MPI_Comm_size(MPI_COMM_WORLD, &n);"; ...
"    return n;"; ...
"#else"; ...
"    return 1;"; ...
"#endif"; ...
"}"; ...
""; ...
"int run_text2code(const std::filesystem::path& pdeapp)"; ...
"{"; ...
"#ifndef EXASIM_TEXT2CODE_EXECUTABLE"; ...
"    const char* text2code = ""text2code"";"; ...
"#else"; ...
"    const char* text2code = EXASIM_TEXT2CODE_EXECUTABLE;"; ...
"#endif"; ...
"    const std::string cmd = quote(text2code) + "" "" + quote(pdeapp);"; ...
"    return std::system(cmd.c_str());"; ...
"}"; ...
"}"; ...
""; ...
"int main(int argc, char** argv)"; ...
"{"; ...
"#ifdef HAVE_MPI"; ...
"    MPI_Init(&argc, &argv);"; ...
"    MPI_Comm comm = MPI_COMM_WORLD;"; ...
"#else"; ...
"    MPI_Comm comm = MPI_COMM_NULL;"; ...
"#endif"; ...
""; ...
"    const int rank = rank_world();"; ...
"    if (argc < 5 || ((argc - 1) % 2) != 0) {"; ...
"        if (rank == 0)"; ...
"            std::cerr << ""Usage: "" << argv[0] << "" pdeapp1.txt ranks1 pdeapp2.txt ranks2\n"";"; ...
"#ifdef HAVE_MPI"; ...
"        MPI_Finalize();"; ...
"#endif"; ...
"        return 1;"; ...
"    }"; ...
""; ...
"    const int nmodels = (argc - 1) / 2;"; ...
"    if (nmodels != 2) {"; ...
"        if (rank == 0)"; ...
"            std::cerr << ""This generated runtime parsed "" << nmodels"; ...
"                      << "" models, but the current Exasim split-domain coupled solver supports exactly 2.\n"";"; ...
"#ifdef HAVE_MPI"; ...
"        MPI_Finalize();"; ...
"#endif"; ...
"        return 1;"; ...
"    }"; ...
""; ...
"    std::vector<std::filesystem::path> pdeapps;"; ...
"    std::vector<int> ranks;"; ...
"    pdeapps.reserve(nmodels);"; ...
"    ranks.reserve(nmodels);"; ...
"    for (int m = 0; m < nmodels; ++m) {"; ...
"        pdeapps.push_back(std::filesystem::absolute(argv[1 + 2*m]));"; ...
"        ranks.push_back(std::stoi(argv[2 + 2*m]));"; ...
"    }"; ...
"    const int totalRanks = std::accumulate(ranks.begin(), ranks.end(), 0);"; ...
"    if (totalRanks != size_world()) {"; ...
"        if (rank == 0)"; ...
"            std::cerr << ""Rank partition sums to "" << totalRanks"; ...
"                      << "", but MPI job has "" << size_world() << "" ranks.\n"";"; ...
"#ifdef HAVE_MPI"; ...
"        MPI_Finalize();"; ...
"#endif"; ...
"        return 1;"; ...
"    }"; ...
""; ...
"    if (rank == 0) {"; ...
"        for (int m = 0; m < nmodels; ++m) {"; ...
"            const auto& pdeapp = pdeapps[m];"; ...
"            const auto dir = pdeapp.parent_path();"; ...
"            const std::string suffix = std::to_string(m + 1);"; ...
"            if (std::filesystem::exists(dir / (""datain"" + suffix) / ""app.bin""))"; ...
"                continue;"; ...
"            const int err = run_text2code(pdeapp);"; ...
"            if (err != 0) {"; ...
"                std::cerr << ""text2code failed for "" << pdeapp << "" with code "" << err << ""\n"";"; ...
"#ifdef HAVE_MPI"; ...
"                MPI_Abort(MPI_COMM_WORLD, err);"; ...
"#endif"; ...
"                return err;"; ...
"            }"; ...
"        }"; ...
"    }"; ...
"#ifdef HAVE_MPI"; ...
"    MPI_Barrier(MPI_COMM_WORLD);"; ...
"#endif"; ...
""; ...
"    std::vector<std::string> legacy;"; ...
"    legacy.push_back(argv[0]);"; ...
"    legacy.push_back(std::to_string(100 + ranks[0]));"; ...
"    for (int m = 0; m < nmodels; ++m) {"; ...
"        const auto dir = pdeapps[m].parent_path();"; ...
"        const std::string suffix = std::to_string(m + 1);"; ...
"        std::filesystem::create_directories(dir / (""dataout"" + suffix));"; ...
"        legacy.push_back((dir / (""datain"" + suffix)).string() + ""/"");"; ...
"        legacy.push_back((dir / (""dataout"" + suffix) / ""out"").string());"; ...
"    }"; ...
""; ...
"    std::vector<char*> legacyArgv;"; ...
"    legacyArgv.reserve(legacy.size());"; ...
"    for (auto& arg : legacy)"; ...
"        legacyArgv.push_back(arg.data());"; ...
""; ...
"    ExasimSolver solver;"; ...
"    const int err = RunExasimSolver(solver, static_cast<int>(legacyArgv.size()), legacyArgv.data(), comm);"; ...
"#ifdef HAVE_MPI"; ...
"    MPI_Finalize();"; ...
"#endif"; ...
"    return err;"; ...
"}"; ...
""];

write_lines(dest + "/CMakeLists.txt", cmake);
write_lines(dest + "/main.cpp", maincpp);
end

function write_lines(path, lines)
fid = fopen(char(path), 'w');
if fid == -1
    error("Unable to write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', lines);
end

function write_text2code_readme(dest, isCoupled, nmodels)
txt = [
"# Exasim Text2Code Export"; ...
""; ...
"This directory contains the high-level Text2Code inputs exported from an Exasim frontend."; ...
""; ...
"Generated files:"; ...
""; ...
"- `pdemodel.txt`: PDE model definition consumed by Text2Code."; ...
"- `pdeapp.txt`: application, mesh, solver, output, and runtime configuration."; ...
"- `grid.bin`: mesh coordinates and connectivity."; ...
"- `xdg.bin`, `udg.bin`, `vdg.bin`, `wdg.bin`: optional field data written only when present."; ...
"- `materialdatabase.bin`: optional material-property database packaged when `pde.materialdatabase` is specified."; ...
""; ...
"Regenerate the application with:"; ...
""; ...
"```sh"; ...
"/path/to/exasim-prefix/bin/text2code pdeapp.txt"; ...
"```"; ...
""; ...
"The `vdg.bin` file stores external variables. In backend data structures these are also called `odg`."; ...
""];
if isCoupled
    txt = [
        txt; ...
        "Coupled export:"; ...
        ""; ...
        "- This package contains " + num2str(nmodels) + " coupled model definitions (`pdeapp*.txt`, `pdemodel*.txt`, `grid*.bin`)."; ...
        "- Coupled material databases, when present, use model-specific names such as `materialdatabase1.bin`."; ...
        "- Configure and build the generated runtime with `cmake -S . -B build -DExasim_DIR=/path/to/exasim-prefix`."; ...
        "- Run the two-domain coupled solver with `mpirun -np 7 build/exasimapp pdeapp1.txt 3 pdeapp2.txt 4`."; ...
        ""];
end

fid = fopen(char(dest + "/README.md"), 'w');
if fid == -1
    error("Unable to write %s.", dest + "/README.md");
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', txt);
end
