// Generated by MATLAB exporttext2code for a coupled Text2Code application.
// Runtime syntax:
//   mpirun -np <sum ranks> build/exasimapp pdeapp1.txt <ranks1> pdeapp2.txt <ranks2>
#include <cstdlib>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <numeric>
#include <string>
#include <vector>

#include <exasim/ExasimSolverSetup.hpp>

namespace {
std::string quote(const std::filesystem::path& p)
{
    return std::string(1, char(34)) + p.string() + std::string(1, char(34));
}

int rank_world()
{
#ifdef HAVE_MPI
    int r = 0;
    MPI_Comm_rank(MPI_COMM_WORLD, &r);
    return r;
#else
    return 0;
#endif
}

int size_world()
{
#ifdef HAVE_MPI
    int n = 1;
    MPI_Comm_size(MPI_COMM_WORLD, &n);
    return n;
#else
    return 1;
#endif
}

int count_model_mesh_partitions(const std::filesystem::path& datain)
{
    std::error_code ec;
    if (!std::filesystem::is_directory(datain, ec))
        return 0;

    int count = 0;
    for (const auto& entry : std::filesystem::directory_iterator(datain, ec)) {
        if (ec)
            break;
        const std::string name = entry.path().filename().generic_string();
        if (name.rfind("mesh", 0) == 0 && entry.path().extension() == ".bin")
            ++count;
    }
    return count;
}

int write_runtime_pdeapp(const std::filesystem::path& source,
                         const std::filesystem::path& generated,
                         const int ranks,
                         const int modelIndex)
{
    std::ifstream in(source);
    if (!in)
        return 1;
    std::ofstream out(generated);
    if (!out)
        return 1;

    out << in.rdbuf();
    out << "\n";
    out << "datapath = " << quote(source.parent_path()) << ";\n";
    out << "datainpath = \"datain" << modelIndex << "\";\n";
    out << "dataoutpath = \"dataout" << modelIndex << "\";\n";
    out << "mpiprocs = " << ranks << ";\n";
    return 0;
}

int run_text2code(const std::filesystem::path& pdeapp)
{
#ifndef EXASIM_TEXT2CODE_EXECUTABLE
    const char* text2code = "text2code";
#else
    const char* text2code = EXASIM_TEXT2CODE_EXECUTABLE;
#endif
    const std::string cmd = quote(text2code) + " " + quote(pdeapp);
    return std::system(cmd.c_str());
}

std::filesystem::path read_quoted_assignment(const std::filesystem::path& pdeapp, const std::string& key)
{
    std::ifstream in(pdeapp);
    std::string line;
    const std::string prefix = key + " = ";
    while (std::getline(in, line)) {
        const auto pos = line.find(prefix);
        if (pos == std::string::npos)
            continue;
        const auto first = line.find('"', pos + prefix.size());
        if (first == std::string::npos)
            return {};
        const auto second = line.find('"', first + 1);
        if (second == std::string::npos)
            return {};
        return pdeapp.parent_path() / line.substr(first + 1, second - first - 1);
    }
    return {};
}

int read_int_assignment(const std::filesystem::path& pdeapp, const std::string& key, int defaultValue = 0)
{
    std::ifstream in(pdeapp);
    std::string line;
    const std::string prefix = key + " = ";
    while (std::getline(in, line)) {
        const auto pos = line.find(prefix);
        if (pos == std::string::npos)
            continue;
        try {
            return std::stoi(line.substr(pos + prefix.size()));
        }
        catch (...) {
            return defaultValue;
        }
    }
    return defaultValue;
}

bool preprocessing_is_stale(const std::filesystem::path& pdeapp, const std::filesystem::path& appbin)
{
    if (!std::filesystem::exists(appbin))
        return true;
    const auto appTime = std::filesystem::last_write_time(appbin);
    if (std::filesystem::last_write_time(pdeapp) > appTime)
        return true;
    const auto pdemodel = read_quoted_assignment(pdeapp, "modelfile");
    return !pdemodel.empty() && std::filesystem::exists(pdemodel)
        && std::filesystem::last_write_time(pdemodel) > appTime;
}
}

int main(int argc, char** argv)
{
#ifdef HAVE_MPI
    MPI_Init(&argc, &argv);
    MPI_Comm comm = MPI_COMM_WORLD;
#else
    MPI_Comm comm = MPI_COMM_NULL;
#endif

    const int rank = rank_world();
    if (argc < 5 || ((argc - 1) % 2) != 0) {
        if (rank == 0)
            std::cerr << "Usage: " << argv[0] << " pdeapp1.txt ranks1 pdeapp2.txt ranks2\n";
#ifdef HAVE_MPI
        MPI_Finalize();
#endif
        return 1;
    }

    const int nmodels = (argc - 1) / 2;
    if (nmodels != 2) {
        if (rank == 0)
            std::cerr << "This generated runtime parsed " << nmodels
                      << " models, but the current Exasim split-domain coupled solver supports exactly 2.\n";
#ifdef HAVE_MPI
        MPI_Finalize();
#endif
        return 1;
    }

    std::vector<std::filesystem::path> pdeapps;
    std::vector<int> ranks;
    pdeapps.reserve(nmodels);
    ranks.reserve(nmodels);
    for (int m = 0; m < nmodels; ++m) {
        pdeapps.push_back(std::filesystem::absolute(argv[1 + 2*m]));
        ranks.push_back(std::stoi(argv[2 + 2*m]));
    }
    const int totalRanks = std::accumulate(ranks.begin(), ranks.end(), 0);
    if (totalRanks != size_world()) {
        if (rank == 0)
            std::cerr << "Rank partition sums to " << totalRanks
                      << ", but MPI job has " << size_world() << " ranks.\n";
#ifdef HAVE_MPI
        MPI_Finalize();
#endif
        return 1;
    }

    if (rank == 0) {
        for (int m = 0; m < nmodels; ++m) {
            const auto& pdeapp = pdeapps[m];
            const auto dir = pdeapp.parent_path();
            const std::string suffix = std::to_string(m + 1);
            const auto datain = dir / ("datain" + suffix);
            const auto appbin = datain / "app.bin";
            if (!preprocessing_is_stale(pdeapp, appbin) &&
                count_model_mesh_partitions(datain) == ranks[m])
                continue;
            std::filesystem::remove_all(datain);
            const auto generatedPdeapp =
                dir / (".exasim_runtime_pdeapp" + suffix + "_np" + std::to_string(ranks[m]) + ".txt");
            int err = write_runtime_pdeapp(pdeapp, generatedPdeapp, ranks[m], m + 1);
            if (err != 0) {
                std::cerr << "failed to write runtime pdeapp " << generatedPdeapp << "\n";
#ifdef HAVE_MPI
                MPI_Abort(MPI_COMM_WORLD, err);
#endif
                return err;
            }
            err = run_text2code(generatedPdeapp);
            std::filesystem::remove(generatedPdeapp);
            if (err != 0) {
                if (std::filesystem::exists(appbin)) {
                    std::cerr << "text2code failed for " << pdeapp << " with code " << err
                              << "; continuing with existing " << appbin << "\n";
                    continue;
                }
                std::cerr << "text2code failed for " << pdeapp << " with code " << err << "\n";
#ifdef HAVE_MPI
                MPI_Abort(MPI_COMM_WORLD, err);
#endif
                return err;
            }
        }
    }
#ifdef HAVE_MPI
    MPI_Barrier(MPI_COMM_WORLD);
#endif

    std::vector<std::string> legacy;
    legacy.push_back(argv[0]);
    legacy.push_back(std::to_string(100 + ranks[0]));
    for (int m = 0; m < nmodels; ++m) {
        const auto dir = pdeapps[m].parent_path();
        const std::string suffix = std::to_string(m + 1);
        std::filesystem::create_directories(dir / ("dataout" + suffix));
        legacy.push_back((dir / ("datain" + suffix)).string() + "/");
        legacy.push_back((dir / ("dataout" + suffix) / "out").string());
    }
    int nsca = 0;
    int nvec = 0;
    int nten = 0;
    int nsurf = 0;
    int nvqoi = 0;
    int saveParaview = 0;
    for (const auto& pdeapp : pdeapps) {
        nsca = std::max(nsca, read_int_assignment(pdeapp, "nsca"));
        nvec = std::max(nvec, read_int_assignment(pdeapp, "nvec"));
        nten = std::max(nten, read_int_assignment(pdeapp, "nten"));
        nsurf = std::max(nsurf, read_int_assignment(pdeapp, "nsurf"));
        nvqoi = std::max(nvqoi, read_int_assignment(pdeapp, "nvqoi"));
        saveParaview = std::max(saveParaview, read_int_assignment(pdeapp, "saveParaview"));
    }
    legacy.push_back("0"); // restart
    legacy.push_back("0"); // postprocess mode
    legacy.push_back(std::to_string(nsca));
    legacy.push_back(std::to_string(nvec));
    legacy.push_back(std::to_string(nten));
    legacy.push_back(std::to_string(nsurf));
    legacy.push_back(std::to_string(nvqoi));
    legacy.push_back(std::to_string(saveParaview));

    std::vector<char*> legacyArgv;
    legacyArgv.reserve(legacy.size());
    for (auto& arg : legacy)
        legacyArgv.push_back(arg.data());

    ExasimSolver solver;
    const int err = RunExasimSolver(solver, static_cast<int>(legacyArgv.size()), legacyArgv.data(), comm);
#ifdef HAVE_MPI
    MPI_Finalize();
#endif
    return err;
}
