# End-to-end schedules (phase 1): the element residual generated per production block; uhat/q/w/faces/scatter via Exasim.
from gen import S, gemm, pt, el, fe
SCHEDULES = [
    S("e2e_ref", [gemm("interp"), pt("source"), pt("time"), pt("flux"), pt("scale"), gemm("integrate")], note="production element sequence, regenerated"),
    S("e2e_ref_kk", [gemm("interp"), pt("source"), pt("time"), pt("flux"), pt("scale"), gemm("integrate")], backend="kokkos"),
    S("e2e_light", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")]),
    S("e2e_ptall", [pt("interp", "source", "time", "flux", "scale"), gemm("integrate")]),
    S("e2e_el2", [el(2, "interp", "source", "time", "flux", "scale", "integrate")]),
    S("e2e_el7w3", [el(7, "interp", "source", "time", "flux", "scale", "integrate", waves=3)]),
    # --- phase 2: generated face residual (element part from Exasim, then with the best element schedule) ---
    S("e2e_face_reg", [], face=dict(hand="reg")),
    S("e2e_face_lds", [], face=dict(hand="lds")),
    S("e2e_face_glb", [], face=dict(hand="glb")),
    S("e2e_face_reg_lb2", [], face=dict(hand="reg", lb=2)),
    S("e2e_face_split", [], face=dict(mode="split")),
    S("e2e_face_split_b2", [], face=dict(mode="split", lbi=2)),
    S("e2e_light_split", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split")),
    # --- phase 3: generated q path (RqElem + gather + Minv + insert; RqFace from Exasim) ---
    S("e2e_q", [], q=dict(v=1)),
    S("e2e_q2", [], q=dict(v=2)),
    S("e2e_q2_lb2", [], q=dict(v=2, lb=2)),
    S("e2e_all3", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=2)),
    S("e2e_all4", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=2), scatter=True),
    # --- the rest: uhat, RqFace, GetW generated too -> every stage of the residual generated ---
    S("e2e_all", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=2),
      scatter=True, uhat=True, rqface=True, w=True, note="fully generated residual"),
    S("e2e_allf", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=2),
      scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fully generated + uhat/RqFace only where the halo changes them"),
    S("e2e_allf3", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=3),
      scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="+ q contractions on the matrix cores"),
    # --- register relief: flux+scale split by conserved component (each kernel keeps only the flux it needs) ---
    S("e2e_allf3k2", [gemm("interp"), pt("source", "time")] + [pt("flux", "scale", ksel=(i, 2)) for i in range(2)] + [gemm("integrate")],
      face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="e2e_allf3, flux in 2 component parts"),
    S("e2e_allf3k3", [gemm("interp"), pt("source", "time")] + [pt("flux", "scale", ksel=(i, 3)) for i in range(3)] + [gemm("integrate")],
      face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="e2e_allf3, flux in 3 component parts"),
    # --- fusion: the whole element chain in one kernel (MFMA interp/integrate through LDS) ---
    S("e2e_fe2", [fe(2)], face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="e2e_allf3 + fused element E=2"),
    S("e2e_fi", [fe(1)], face=dict(mode="split", fi=True), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1 + face interp fused into the flux kernels"),
    S("e2e_fi1", [fe(1)], face=dict(mode="split", fi=True, lb=1), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="e2e_fi, 1-wave flux"),
    S("e2e_q4", [fe(1, lb=2)], face=dict(mode="split"), q=dict(v=4), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2 + q interpolation on MFMA"),
    S("e2e_rq2", [fe(1, lb=2)], face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=2, w=True, fsel=True, note="fe1b2 + rqface v2"),
    S("e2e_q4rq2", [fe(1, lb=2)], face=dict(mode="split"), q=dict(v=4), scatter=True, uhat=True, rqface=2, w=True, fsel=True, note="fe1b2 + both"),
    S("e2e_fs", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="staged"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="q6l2 + staged face interpolation"),
    S("e2e_fsr4", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="staged"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, note="e2e_fs + one-launch rqface"),
    S("e2e_bat", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="staged"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_fsr4 + one launch per range for elem and q"),
    S("e2e_bat2", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="staged"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_bat (+ interior faces batched when MK_FACE_ALL)"),
    S("e2e_conn", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_bat2 + per-node-connectivity face interpolation"),
    S("e2e_q7", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn"), q=dict(v=7, lb=2), scatter=True, uhat=True, rqface=False, w=True, fsel=True, batch=True, note="e2e_conn + face integrals inside the q kernel (no RqFace)"),
    S("e2e_q8", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn"), q=dict(v=8, lb=2), scatter=True, uhat=True, rqface=False, w=True, fsel=True, batch=True, note="e2e_q7 with the faces in parallel"),
    S("e2e_q9", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn"), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_conn, pass-2 q with in-kernel faces"),
    S("e2e_c1_64", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", sfb=1, tpb=64), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_q9, interp 1 faces x 64 threads"),
    S("e2e_c2_128", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", sfb=2, tpb=128), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_q9, interp 2 faces x 128 threads"),
    S("e2e_c2_256", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", sfb=2, tpb=256), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_q9, interp 2 faces x 256 threads"),
    S("e2e_c4_128", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", sfb=4, tpb=128), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_q9, interp 4 faces x 128 threads"),
    S("e2e_c8_256", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", sfb=8, tpb=256), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_q9, interp 8 faces x 256 threads"),
    S("e2e_prod", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", producer=True), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_q9 + face values written by the element kernel"),
    S("e2e_prod1", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", producer=True, punroll=1), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_prod, column loop not unrolled"),
    S("e2e_prod8", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", producer=True, punroll=8), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_prod, column loop unrolled 8"),
    S("e2e_prodg", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", producer=True, plds=False), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_prod with the element interp still gathering from global (A/B)"),
    S("e2e_pm", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", producer=True, pmfma=True), q=dict(v=9, lb=2), scatter=True, uhat=True, rqface=4, w=True, fsel=True, batch=True, note="e2e_prod with the face values on the matrix cores (rounding-level)"),
    S("e2e_q10", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="conn", producer=True), q=dict(v=10, lb=2), scatter=True, uhat=True, rqface=False, w=True, fsel=True, batch=True, note="e2e_prod with the q face term inside the MFMA chain (rounding-level)"),
    S("e2e_rq3", [fe(1, lb=2, sf=True)], face=dict(mode="split"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=3, w=True, fsel=True, note="q6l2 + rqface v3"),
    S("e2e_fsrq3", [fe(1, lb=2, sf=True)], face=dict(mode="split", interp="staged"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=3, w=True, fsel=True, note="q6l2 + both"),
    S("e2e_q6", [fe(1, lb=2, sf=True)], face=dict(mode="split"), q=dict(v=6), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="e2e_sf + q v6 (R in registers)"),
    S("e2e_q6l2", [fe(1, lb=2, sf=True)], face=dict(mode="split"), q=dict(v=6, lb=2), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="e2e_sf + q v6, 2-wave hint"),
    S("e2e_sf", [fe(1, lb=2, sf=True)], face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2 with the source+flux combined body"),
    S("e2e_q5", [fe(1, lb=2)], face=dict(mode="split"), q=dict(v=5), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2 + q v5 (MFMA interp + staged gather)"),
    S("e2e_q5rq2", [fe(1, lb=2)], face=dict(mode="split"), q=dict(v=5), scatter=True, uhat=True, rqface=2, w=True, fsel=True, note="q v5 + rqface v2"),
    S("e2e_q4ng", [fe(1, lb=2)], face=dict(mode="split"), q=dict(v=4, nogather=True), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="TIMING ABLATION: q without face gather (wrong)"),
    S("e2e_fib2", [fe(1, lb=2)], face=dict(mode="split", fi=True, lb=2), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2 + face interp fused into flux kernels (lb 2)"),
    S("e2e_fib1", [fe(1, lb=2)], face=dict(mode="split", fi=True, lb=1), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2 + face interp fused into flux kernels (lb 1)"),
    S("e2e_fh32", [fe(1, lb=2)], face=dict(mode="split", lb=3, lbi=2), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2, face hint 3 / boundary 2"),
    S("e2e_fh22", [fe(1, lb=2)], face=dict(mode="split", lb=2, lbi=2), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2, face hint 2 / boundary 2"),
    S("e2e_fh31", [fe(1, lb=2)], face=dict(mode="split", lb=3, lbi=1), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fe1b2, face hint 3 / boundary 1"),
    S("e2e_fe1b2", [fe(1, lb=2)], face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fused element E=1, 2 waves"),
    S("e2e_fe2b2", [fe(2, lb=2)], face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="fused element E=2, 2 waves"),
    S("e2e_fe1", [fe(1)], face=dict(mode="split"), q=dict(v=3), scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="e2e_allf3 + fused element E=1"),
    S("e2e_allf3g", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split", interp="gemm"), q=dict(v=3),
      scatter=True, uhat=True, rqface=True, w=True, fsel=True, note="+ face interpolation as gather + MFMA GEMM"),
    S("e2e_all_uh", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=2),
      scatter=True, uhat=True),
    S("e2e_all_rq", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=2),
      scatter=True, rqface=True),
    S("e2e_all_w", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(mode="split"), q=dict(v=2),
      scatter=True, w=True),
    S("e2e_light_facereg", [gemm("interp"), pt("source", "time"), pt("flux", "scale"), gemm("integrate")], face=dict(hand="reg")),
]
