#include <cstdio>
#include <cstdlib>

#include "libbuiltinmodel.hpp"
// Built-in model set (includes + EXASIM_BUILTIN_MODELS macro),
// generated by CMake from the registered model IDs.
#define EXASIM_BUILTIN_MODEL_IMPL
#include "builtin_model_registry.h"



// ----------------------------- Kokkos -----------------------------

extern "C"
void builtinKokkosFlux(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                const dstype* wdg, const dstype* uinf, const dstype* param,
                dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosFlux(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosFlux\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosAvfield(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                   const dstype* wdg, const dstype* uinf, const dstype* param,
                   dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                   int ncx, int nco, int ncw, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosAvfield(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosAvfield\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosEoS(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
               const dstype* wdg, const dstype* uinf, const dstype* param,
               dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
               int ncx, int nco, int ncw, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosEoS(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosEoS\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosEoSdu(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                 const dstype* wdg, const dstype* uinf, const dstype* param,
                 dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                 int ncx, int nco, int ncw, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosEoSdu(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosEoSdu\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosEoSdw(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                 const dstype* wdg, const dstype* uinf, const dstype* param,
                 dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                 int ncx, int nco, int ncw, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosEoSdw(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosEoSdw\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosFbou(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                const dstype* wdg, const dstype* uhg, const dstype* nlg, const dstype* tau,
                const dstype* uinf, const dstype* param, dstype time, int builtinmodelID,
                int ib, int ng, int nc, int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosFbou(f, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosFbou\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosFbouJac(dstype* f, dstype* f_udg, dstype* f_wdg, dstype* f_uhg,
                const dstype* xdg, const dstype* udg, const dstype* odg,
                const dstype* wdg, const dstype* uhg, const dstype* nlg,
                const dstype* tau, const dstype* uinf, const dstype* param,
                dstype time, int builtinmodelID, int ib, int ng, int nc,
                int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosFbouJac(f, f_udg, f_wdg, f_uhg, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosFbouJac\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosFhat(dstype* f, const dstype* xdg, const dstype* udg1, const dstype* udg2,
                const dstype* odg1, const dstype* odg2, const dstype* wdg1, const dstype* wdg2,
                const dstype* uhg, const dstype* nlg, const dstype* tau, const dstype* uinf,
                const dstype* param, dstype time, int builtinmodelID, int ng, int nc, int ncu,
                int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosFhat(f, xdg, udg1, udg2, odg1, odg2, wdg1, wdg2, uhg, nlg, tau, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosFhat\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosInitodg(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                   int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosInitodg(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosInitodg\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosInitq(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                 int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosInitq(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosInitq\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosInitu(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                 int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosInitu(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosInitu\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosInitudg(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                   int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosInitudg(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosInitudg\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosInitwdg(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                   int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosInitwdg(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosInitwdg\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosMonitor(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                   const dstype* wdg, const dstype* uinf, const dstype* param,
                   dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                   int ncx, int nco, int ncw, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosMonitor(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosMonitor\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosOutput(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                  const dstype* wdg, const dstype* uinf, const dstype* param,
                  dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                  int ncx, int nco, int ncw, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosOutput(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosOutput\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosSource(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                  const dstype* wdg, const dstype* uinf, const dstype* param,
                  dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                  int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosSource(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosSource\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosSourcew(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                   const dstype* wdg, const dstype* uinf, const dstype* param,
                   dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                   int ncx, int nco, int ncw, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosSourcew(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosSourcew\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosStab(dstype* f, const dstype* xdg, const dstype* udg1, const dstype* udg2,
                const dstype* odg1, const dstype* odg2, const dstype* wdg1, const dstype* wdg2,
                const dstype* uhg, const dstype* nlg, const dstype* tau, const dstype* uinf,
                const dstype* param, dstype time, int builtinmodelID, int ng, int nc, int ncu,
                int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosStab(f, xdg, udg1, udg2, odg1, odg2, wdg1, wdg2, uhg, nlg, tau, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosStab\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosMaterialstate(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                  const dstype* wdg, const dstype* uinf, const dstype* param,
                  dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                  int ncx, int nco, int ncw, int nmaterialstate)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosMaterialstate(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nmaterialstate); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosMaterialstate\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosTdfunc(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                  const dstype* wdg, const dstype* uinf, const dstype* param,
                  dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                  int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosTdfunc(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosTdfunc\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosUbou(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                const dstype* wdg, const dstype* uhg, const dstype* nlg, const dstype* tau,
                const dstype* uinf, const dstype* param, dstype time, int builtinmodelID, int ib,
                int ng, int nc, int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosUbou(f, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosUbou\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosUbouJac(dstype* f, dstype* f_udg, dstype* f_wdg, dstype* f_uhg,
                const dstype* xdg, const dstype* udg, const dstype* odg,
                const dstype* wdg, const dstype* uhg, const dstype* nlg,
                const dstype* tau, const dstype* uinf, const dstype* param,
                dstype time, int builtinmodelID, int ib, int ng, int nc,
                int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosUbouJac(f, f_udg, f_wdg, f_uhg, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosUbouJac\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosUhat(dstype* f, const dstype* xdg, const dstype* udg1, const dstype* udg2,
                const dstype* odg1, const dstype* odg2, const dstype* wdg1, const dstype* wdg2,
                const dstype* uhg, const dstype* nlg, const dstype* tau, const dstype* uinf,
                const dstype* param, dstype time, int builtinmodelID, int ng, int nc, int ncu,
                int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosUhat(f, xdg, udg1, udg2, odg1, odg2, wdg1, wdg2, uhg, nlg, tau, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosUhat\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosVisScalars(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                      const dstype* wdg, const dstype* uinf, const dstype* param,
                      dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                      int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosVisScalars(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosVisScalars\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosVisVectors(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                      const dstype* wdg, const dstype* uinf, const dstype* param,
                      dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                      int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosVisVectors(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosVisVectors\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosVisTensors(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                      const dstype* wdg, const dstype* uinf, const dstype* param,
                      dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                      int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosVisTensors(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosVisTensors\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosQoIvolume(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                     const dstype* wdg, const dstype* uinf, const dstype* param,
                     dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd,
                     int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosQoIvolume(f, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosQoIvolume\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinKokkosQoIboundary(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                       const dstype* wdg, const dstype* uhg, const dstype* nlg, const dstype* tau,
                       const dstype* uinf, const dstype* param, dstype time, int builtinmodelID,
                       int ib, int ng, int nc, int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::KokkosQoIboundary(f, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in KokkosQoIboundary\n", builtinmodelID); std::abort();
    }
}

// ----------------------------- cpuInit* -----------------------------

extern "C"
void builtincpuInitodg(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::cpuInitodg(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in cpuInitodg\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtincpuInitq(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
              int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::cpuInitq(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in cpuInitq\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtincpuInitu(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
              int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::cpuInitu(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in cpuInitu\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtincpuInitudg(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::cpuInitudg(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in cpuInitudg\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtincpuInitwdg(dstype* f, const dstype* xdg, const dstype* uinf, const dstype* param,
                int builtinmodelID, int ng, int ncx, int nce, int npe, int ne)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::cpuInitwdg(f, xdg, uinf, param, builtinmodelID, ng, ncx, nce, npe, ne); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in cpuInitwdg\n", builtinmodelID); std::abort();
    }
}

// ----------------------------- HDG -----------------------------

extern "C"
void builtinHdgEoS(dstype* f, dstype* f_udg, dstype* f_wdg, const dstype* xdg, const dstype* udg,
            const dstype* odg, const dstype* wdg, const dstype* uinf, const dstype* param,
            dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd, int ncx,
            int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgEoS(f, f_udg, f_wdg, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgEoS\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgFbou(dstype* f, dstype* f_udg, dstype* f_wdg, dstype* f_uhg, const dstype* xdg,
             const dstype* udg, const dstype* odg, const dstype* wdg, const dstype* uhg,
             const dstype* nlg, const dstype* tau, const dstype* uinf, const dstype* param,
             dstype time, int builtinmodelID, int ib, int ng, int nc, int ncu, int nd,
             int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgFbou(f, f_udg, f_wdg, f_uhg, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgFbou\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgFbouonly(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                 const dstype* wdg, const dstype* uhg, const dstype* nlg, const dstype* tau,
                 const dstype* uinf, const dstype* param, dstype time, int builtinmodelID,
                 int ib, int ng, int nc, int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgFbouonly(f, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgFbouonly\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgFint(dstype* f, dstype* f_udg, dstype* f_wdg, dstype* f_uhg, const dstype* xdg,
             const dstype* udg, const dstype* odg, const dstype* wdg, const dstype* uhg,
             const dstype* nlg, const dstype* tau, const dstype* uinf, const dstype* param,
             dstype time, int builtinmodelID, int ib, int ng, int nc, int ncu, int nd,
             int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgFint(f, f_udg, f_wdg, f_uhg, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgFint\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgFintonly(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                 const dstype* wdg, const dstype* uhg, const dstype* nlg, const dstype* tau,
                 const dstype* uinf, const dstype* param, dstype time, int builtinmodelID,
                 int ib, int ng, int nc, int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgFintonly(f, xdg, udg, odg, wdg, uhg, nlg, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgFintonly\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgFext(dstype* f, dstype* f_udg, dstype* f_wdg, dstype* f_uhg, const dstype* xdg,
             const dstype* udg, const dstype* odg, const dstype* wdg, const dstype* uhg,
             const dstype* nlg, const dstype* uext, const dstype* tau, const dstype* uinf,
             const dstype* param, dstype time, int builtinmodelID, int ib, int ng, int nc,
             int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgFext(f, f_udg, f_wdg, f_uhg, xdg, udg, odg, wdg, uhg, nlg, uext, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgFext\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgFextonly(dstype* f, const dstype* xdg, const dstype* udg, const dstype* odg,
                 const dstype* wdg, const dstype* uhg, const dstype* nlg, const dstype* uext,
                 const dstype* tau, const dstype* uinf, const dstype* param,
                 dstype time, int builtinmodelID, int ib, int ng, int nc, int ncu, int nd,
                 int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgFextonly(f, xdg, udg, odg, wdg, uhg, nlg, uext, tau, uinf, param, time, builtinmodelID, ib, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgFextonly\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgFlux(dstype* f, dstype* f_udg, dstype* f_wdg, const dstype* xdg, const dstype* udg,
             const dstype* odg, const dstype* wdg, const dstype* uinf, const dstype* param,
             dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd, int ncx,
             int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgFlux(f, f_udg, f_wdg, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgFlux\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgSource(dstype* f, dstype* f_udg, dstype* f_wdg, const dstype* xdg, const dstype* udg,
               const dstype* odg, const dstype* wdg, const dstype* uinf, const dstype* param,
               dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd, int ncx,
               int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgSource(f, f_udg, f_wdg, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgSource\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgMaterialstate(dstype* f, dstype* f_udg, dstype* f_wdg, const dstype* xdg,
               const dstype* udg, const dstype* odg, const dstype* wdg, const dstype* uinf,
               const dstype* param, dstype time, int builtinmodelID, int ng, int nc, int ncu,
               int nd, int ncx, int nco, int ncw, int nmaterialstate)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgMaterialstate(f, f_udg, f_wdg, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw, nmaterialstate); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgMaterialstate\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgSourcew(dstype* f, dstype* f_udg, dstype* f_wdg, const dstype* xdg, const dstype* udg,
                const dstype* odg, const dstype* wdg, const dstype* uinf, const dstype* param,
                dstype time, int builtinmodelID, int ng, int nc, int ncu, int nd, int ncx,
                int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgSourcew(f, f_udg, f_wdg, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgSourcew\n", builtinmodelID); std::abort();
    }
}

extern "C"
void builtinHdgSourcewonly(dstype* f, dstype* f_wdg, const dstype* xdg, const dstype* udg,
                    const dstype* odg, const dstype* wdg, const dstype* uinf,
                    const dstype* param, dstype time, int builtinmodelID, int ng, int nc,
                    int ncu, int nd, int ncx, int nco, int ncw)
{
    switch (builtinmodelID) {
      #define EXASIM_DISPATCH_CASE(N) case N: exasim_model_##N::HdgSourcewonly(f, f_wdg, xdg, udg, odg, wdg, uinf, param, time, builtinmodelID, ng, nc, ncu, nd, ncx, nco, ncw); return;
      EXASIM_BUILTIN_MODELS(EXASIM_DISPATCH_CASE)
      #undef EXASIM_DISPATCH_CASE
      default: std::fprintf(stderr, "ERROR: Unknown builtinmodelID=%d in HdgSourcewonly\n", builtinmodelID); std::abort();
    }
}
