// Auto-generated by text2code. Do not edit by hand.
// Regenerate with `text2code <pdeapp.txt>`.
//
// This header is consumed by `<exasim/model.hpp>`'s templated FEM
// internals. The struct below satisfies the Model contract; the
// inherited `ModelDefaults<GeneratedModel>` supplies zero-fill
// defaults for any optional method this PDE doesn't define.
#pragma once

#include <Kokkos_Core.hpp>
struct PdeModel : ModelDefaults<PdeModel> {
    static constexpr int nd     = 2;
    static constexpr int ncu    = 2;
    static constexpr int ncw    = 0;
    static constexpr int nco    = 2;
    static constexpr int nparam = 2;
    static constexpr int ntau   = 2;
    static constexpr int Nq = ncu * (1 + nd);

    KOKKOS_INLINE_FUNCTION static
    void flux(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];

        f[0] = uq2*mu0;
        f[1] = uq3*mu0;
        f[2] = uq4*mu1;
        f[3] = uq5*mu1;
    }

    KOKKOS_INLINE_FUNCTION static
    void source(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 0.0;
        f[1] = 0.0;
    }

    KOKKOS_INLINE_FUNCTION static
    void tdfunc(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 1;
        f[1] = 1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_scalars(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];

        f[0] = uq0;
        f[1] = uq1;
        f[2] = uq2;
        f[3] = uq3;
        f[4] = uq4;
        f[5] = uq5;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_vectors(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];

        f[0] = uq2;
        f[1] = uq3;
        f[2] = uq4;
        f[3] = uq5;
    }

    KOKKOS_INLINE_FUNCTION static
    void qoi_volume(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x0 = x[0];
        const dstype x1 = x[1];
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];

        f[0] = Kokkos::pow(uq0 - x0, 2);
        f[1] = Kokkos::pow(uq1 - x1, 2);
        f[2] = uq0;
        f[3] = uq1;
    }

    KOKKOS_INLINE_FUNCTION static
    void initu(dstype f[], const dstype x[], const dstype uinf[], const dstype mu[]) {

        f[0] = 0.0;
        f[1] = 0.0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uq3 = uq[3];
            const dstype uq4 = uq[4];
            const dstype uq5 = uq[5];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];
            const dstype mu0 = mu[0];
            const dstype mu1 = mu[1];

            f[0] = tau0*(-uhat0 + uq0) + n0*uq2*mu0 + n1*uq3*mu0;
            f[1] = tau1*(-uhat1 + uq1) + n0*uq4*mu1 + n1*uq5*mu1;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0.0;
            f[1] = 0.0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype x0 = x[0];
            const dstype x1 = x[1];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];

            f[0] = tau0*(-uhat0 + x0 + x1);
            f[1] = tau1*(-uhat1 + x0 - x1);
        }
        else if (ib == 2) {
            const dstype x0 = x[0];
            const dstype x1 = x[1];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];

            f[0] = tau0*(-uhat0 + x0 + x1);
            f[1] = tau1*(-uhat1 + x0 - x1);
        }
        else if (ib == 3) {
            const dstype x0 = x[0];
            const dstype x1 = x[1];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];

            f[0] = tau0*(-uhat0 + x0 + x1);
            f[1] = tau1*(-uhat1 + x0 - x1);
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void qoi_boundary(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uq3 = uq[3];
            const dstype uq4 = uq[4];
            const dstype uq5 = uq[5];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];
            const dstype mu0 = mu[0];
            const dstype mu1 = mu[1];

            f[0] = tau0*(-uhat0 + uq0) + n0*uq2*mu0 + n1*uq3*mu0;
            f[1] = tau1*(-uhat1 + uq1) + n0*uq4*mu1 + n1*uq5*mu1;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void flux_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
        f[4] = 0;
        f[5] = 0;
        f[6] = 0;
        f[7] = 0;
        f[8] = mu0;
        f[9] = 0;
        f[10] = 0;
        f[11] = 0;
        f[12] = 0;
        f[13] = mu0;
        f[14] = 0;
        f[15] = 0;
        f[16] = 0;
        f[17] = 0;
        f[18] = mu1;
        f[19] = 0;
        f[20] = 0;
        f[21] = 0;
        f[22] = 0;
        f[23] = mu1;
    }

    KOKKOS_INLINE_FUNCTION static
    void source_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
        f[4] = 0;
        f[5] = 0;
        f[6] = 0;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = 0;
        f[11] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
        }
        else if (ib == 3) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];

            f[0] = -tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = -tau1;
        }
        else if (ib == 2) {
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];

            f[0] = -tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = -tau1;
        }
        else if (ib == 3) {
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];

            f[0] = -tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = -tau1;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];
            const dstype mu0 = mu[0];
            const dstype mu1 = mu[1];

            f[0] = tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = tau1;
            f[4] = n0*mu0;
            f[5] = 0;
            f[6] = n1*mu0;
            f[7] = 0;
            f[8] = 0;
            f[9] = n0*mu1;
            f[10] = 0;
            f[11] = n1*mu1;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype tau0 = tau[0];
            const dstype tau1 = tau[1];

            f[0] = -tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = -tau1;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

};
