function An = getan3d(nl,m,gam,cas)
gam1 = gam - 1.0;
nx = nl(1);
ny = nl(2);
nz = nl(3);
r = m(1);
ru = m(2);
rv = m(3);
rw = m(4);
rE = m(5);
cy = sqrt(nx^2+ny^2);
sy = nz;
cz = nx/cy;
sz = ny/cy;
Tz = [1, 0, 0, 0, 0;...
      0, cz, sz, 0, 0;...
      0, -sz, cz, 0, 0;...
      0, 0, 0, 1, 0;
      0, 0, 0, 0, 1];
Ty = [1, 0, 0, 0, 0;...
      0, cy, 0, sy, 0;...
      0, 0, 1, 0, 0;...
      0, -sy, 0, cy, 0;
      0, 0, 0, 0, 1];
T = Ty*Tz;
Tinv = (Tz.')*(Ty.');
U = [r, ru, rv, rw, rE].';
TU = T*U;
run = TU(2);
rvn = TU(3);
rwn = TU(4);
un = run/r;
vn = rvn/r;
wn = rwn/r;
P = gam1*(rE - r*(1/2)*(un^2 + vn^2 + wn^2));
a = sqrt(gam*P/r);
H = rE/r + P/r;
K = [ 1 , 1 , 0 , 0, 1 ;...
      un-a , un , 0 , 0, un+a ;...
      vn , vn , 1 , 0, vn ;...
      wn , wn , 0 , 1, wn ;...
      H - un*a , (1/2)*(un^2+vn^2+wn^2) , vn , wn, H+un*a ];
Kinv = (gam1/(2*a^2))*[ H + (a/gam1)*(un-a) , -(un+a/gam1) , -vn , -wn, 1 ;...
                        -2*H + (4/gam1)*a^2 , 2*un , 2*vn , 2*wn, -2 ;...
                        -2*(vn*a^2)/gam1 , 0 , 2*(a^2)/gam1 , 0, 0 ;...
                        -2*wn*a^2/gam1 , 0 , 0 , 2*a^2/gam1, 0
                        H - a*(un+a)/gam1 , -un+a/gam1 , -vn , -wn, 1 ];
if cas==0
    Lambda = [ tanh(1e2*(un-a)) , 0 , 0 , 0 , 0 ;...
                     0 , tanh(1e2*(un)) , 0 , 0 , 0 ;...
                     0 , 0 , tanh(1e2*(un)) , 0 , 0 ;...
                     0 , 0 , 0 , tanh(1e2*(un)), 0 ;...
                     0 , 0 , 0 , 0 , tanh(1e2*(un+a)) ];
else
    Lambda = [ abs(un-a) , 0 , 0 , 0 , 0 ;...
                     0 , abs(un) , 0 , 0 , 0 ;...
                     0 , 0 , abs(un) , 0 , 0 ;...
                     0 , 0 , 0 , abs(un) , 0;...
                     0 , 0 , 0 , 0 , abs(un+a) ];
end
E = K * Lambda * Kinv;
An = Tinv * E * T;