// Auto-generated by text2code. Do not edit by hand.
// Regenerate with `text2code <pdeapp.txt>`.
//
// This header is consumed by `<exasim/model.hpp>`'s templated FEM
// internals. The struct below satisfies the Model contract; the
// inherited `ModelDefaults<GeneratedModel>` supplies zero-fill
// defaults for any optional method this PDE doesn't define.
#pragma once

#include <Kokkos_Core.hpp>
struct PdeModel : ModelDefaults<PdeModel> {
    static constexpr int nd     = 2;
    static constexpr int ncu    = 4;
    static constexpr int ncw    = 0;
    static constexpr int nco    = 1;
    static constexpr int nparam = 12;
    static constexpr int ntau   = 1;
    static constexpr int Nq = ncu * (1 + nd);

    static constexpr bool has_external_coupling = true;
    static constexpr int nfint  = 5;
    static constexpr int nfext  = 4;
    static constexpr int ncuext = 1;

    KOKKOS_INLINE_FUNCTION static
    void flux(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x1 = x[1];
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uq0, -1);
        const dstype x2 = x0*uq2;
        const dstype x3 = x2/x1;
        const dstype x4 = uq10 - x2*uq8;
        const dstype x5 = x0*x4;
        const dstype x6 = x0*uq1;
        const dstype x7 = uq5 - x6*uq4;
        const dstype x8 = x0*x7;
        const dstype x9 = -1.0 + mu0;
        const dstype x10 = Kokkos::pow(uq2, 2);
        const dstype x11 = Kokkos::pow(uq0, -2);
        const dstype x12 = Kokkos::pow(uq1, 2);
        const dstype x13 = 0.5*(x11*x10 + x12*x11);
        const dstype x14 = uq3 - uq0*x13;
        const dstype x15 = x9*x14;
        const dstype x16 = x0*x15;
        const dstype x17 = Kokkos::sqrt(Kokkos::pow(x9, 3)*Kokkos::pow(x14, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3)/Kokkos::pow(uq0, 3))*(110.4 + mu9)/(mu1*(110.4 + 1.0*x16*Kokkos::pow(mu3, 2)*mu9*mu0));
        const dstype x18 = 0.666666666666667*x17;
        const dstype x19 = (x3 - x5 + 2*x8)*x18;
        const dstype x20 = uq6 - x2*uq4;
        const dstype x21 = uq9 - x6*uq8;
        const dstype x22 = 1.0*x17;
        const dstype x23 = (x0*x20 + x0*x21)*x22;
        const dstype x24 = x23 + x2*uq1;
        const dstype x25 = uq2*x11;
        const dstype x26 = uq1*x11;
        const dstype x27 = x9*uq0;
        const dstype x28 = x22*x11*mu0/(x9*mu2);
        const dstype x29 = x16 + x0*uq3;
        const dstype x30 = (x3 + 2*x5 - x8)*x18;

        f[0] = uq1 + v0*uq4;
        f[1] = x15 + x19 + v0*uq5 + x0*x12;
        f[2] = x24 + v0*uq6;
        f[3] = uq1*x29 + v0*uq7 + x2*x23 + x28*(-uq4*x15 + x27*(uq7 - uq0*(x25*x20 + x7*x26) - uq4*x13)) + x6*x19;
        f[4] = uq2 + v0*uq8;
        f[5] = x24 + v0*uq9;
        f[6] = x15 + x30 + v0*uq10 + x0*x10;
        f[7] = uq2*x29 + v0*uq11 + x2*x30 + x28*(-uq8*x15 + x27*(uq11 - uq0*(x21*x26 + x4*x25) - uq8*x13)) + x6*x23;
    }

    KOKKOS_INLINE_FUNCTION static
    void source(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x1 = x[1];
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(x1, -1);
        const dstype x2 = Kokkos::pow(uq0, -1);
        const dstype x3 = x2*uq2;
        const dstype x4 = x2*uq1;
        const dstype x5 = uq9 - x4*uq8;
        const dstype x6 = -1.0 + mu0;
        const dstype x7 = Kokkos::pow(uq2, 2);
        const dstype x8 = Kokkos::pow(uq0, -2);
        const dstype x9 = 0.5*(x8*Kokkos::pow(uq1, 2) + x8*x7);
        const dstype x10 = uq3 - x9*uq0;
        const dstype x11 = x6*x10;
        const dstype x12 = x2*x11;
        const dstype x13 = Kokkos::sqrt(Kokkos::pow(x6, 3)*Kokkos::pow(x10, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3)/Kokkos::pow(uq0, 3))*(110.4 + mu9)/(mu1*(110.4 + 1.0*x12*Kokkos::pow(mu3, 2)*mu9*mu0));
        const dstype x14 = 1.0*x13;
        const dstype x15 = uq10 - x3*uq8;
        const dstype x16 = x2*x15;
        const dstype x17 = -x2*(uq5 - x4*uq4);
        const dstype x18 = x0*x3;
        const dstype x19 = 0.666666666666667*x13;
        const dstype x20 = x19*(2*x16 + x17 + x18);

        f[0] = -x0*(uq2 + v0*uq8);
        f[1] = -x0*(v0*uq9 + x14*(x2*x5 + x2*(uq6 - x3*uq4)) + x4*uq2);
        f[2] = -x0*(x20 + v0*uq10 - x19*(-x16 + x17 - 2*x18) + x2*x7);
        f[3] = -x0*(uq2*(x12 + x2*uq3) + v0*uq11 + x3*x20 + x8*x14*mu0*(-uq8*x11 + x6*uq0*(uq11 - uq0*(x5*x8*uq1 + x8*uq2*x15) - x9*uq8))/(x6*mu2));
    }

    KOKKOS_INLINE_FUNCTION static
    void tdfunc(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 1;
        f[1] = 1;
        f[2] = 1;
        f[3] = 1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_scalars(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uq0, -1);
        const dstype x1 = Kokkos::pow(uq0, -2);
        const dstype x2 = uq3 - 0.5*(x1*Kokkos::pow(uq1, 2) + x1*Kokkos::pow(uq2, 2))*uq0;
        const dstype x3 = x2*(-1.0 + mu0);
        const dstype x4 = x3*Kokkos::pow(mu3, 2)*mu9*mu0;

        f[0] = uq0;
        f[1] = x0*uq1;
        f[2] = x0*uq2;
        f[3] = x3;
        f[4] = x0*x2;
        f[5] = 1.0*x0*x4;
        f[6] = 4.14087039670808e-07*x4*mu1*Kokkos::sqrt(Kokkos::pow(mu9, 3))/(110.4 + mu9);
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_vectors(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];

        f[0] = uq1;
        f[1] = uq2;
    }

    KOKKOS_INLINE_FUNCTION static
    void initu(dstype f[], const dstype x[], const dstype uinf[], const dstype mu[]) {
        const dstype mu4 = mu[4];
        const dstype mu5 = mu[5];
        const dstype mu6 = mu[6];
        const dstype mu7 = mu[7];

        f[0] = mu4;
        f[1] = mu5;
        f[2] = mu6;
        f[3] = mu7;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype mu4 = mu[4];
            const dstype mu5 = mu[5];
            const dstype mu6 = mu[6];
            const dstype mu7 = mu[7];

            f[0] = mu4 - uhat0;
            f[1] = mu5 - uhat1;
            f[2] = mu6 - uhat2;
            f[3] = mu7 - uhat3;
        }
        else if (ib == 2) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uq3 = uq[3];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1 + uq1;
            f[2] = -uhat2 + uq2;
            f[3] = -uhat3 + uq3;
        }
        else if (ib == 3) {
            const dstype uq0 = uq[0];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype mu8 = mu[8];
            const dstype mu9 = mu[9];
            const dstype mu10 = mu[10];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1;
            f[2] = -uhat2;
            f[3] = -uhat3 + mu8*mu10*uhat0/mu9;
        }
        else if (ib == 4) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uq3 = uq[3];
            const dstype uq4 = uq[4];
            const dstype uq5 = uq[5];
            const dstype uq6 = uq[6];
            const dstype uq7 = uq[7];
            const dstype uq8 = uq[8];
            const dstype uq9 = uq[9];
            const dstype uq10 = uq[10];
            const dstype uq11 = uq[11];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];

            f[0] = n0*uq4 + n1*uq8 + tau0*(-uhat0 + uq0);
            f[1] = n0*uq5 + n1*uq9 + tau0*(-uhat1 + uq1);
            f[2] = n0*uq6 + n1*uq10 + tau0*(-uhat2 + uq2);
            f[3] = n0*uq7 + n1*uq11 + tau0*(-uhat3 + uq3);
        }
        else if (ib == 5) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uq3 = uq[3];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];

            const dstype x0 = n0*uq1 + n1*uq2;

            f[0] = tau0*(-uhat0 + uq0);
            f[1] = tau0*(-uhat1 + uq1 - n0*x0);
            f[2] = tau0*(-uhat2 + uq2 - n1*x0);
            f[3] = tau0*(-uhat3 + uq3);
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void flux_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x1 = x[1];
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uq1, 2);
        const dstype x2 = Kokkos::pow(uq0, -2);
        const dstype x3 = x0*x2;
        const dstype x4 = -1.0 + mu0;
        const dstype x5 = Kokkos::pow(uq0, -3);
        const dstype x6 = x0*x5;
        const dstype x7 = Kokkos::pow(uq2, 2);
        const dstype x8 = x5*x7;
        const dstype x9 = 0.5*(-2*x6 - 2*x8);
        const dstype x10 = x2*x7;
        const dstype x11 = -0.5*x10 - 0.5*x3;
        const dstype x12 = x11 - x9*uq0;
        const dstype x13 = x4*x12;
        const dstype x14 = Kokkos::pow(x1, -1);
        const dstype x15 = Kokkos::pow(uq0, -1);
        const dstype x16 = x15*x14;
        const dstype x17 = uq2*x16;
        const dstype x18 = uq2*x15;
        const dstype x19 = uq10 - uq8*x18;
        const dstype x20 = x15*x19;
        const dstype x21 = uq1*x15;
        const dstype x22 = uq5 - uq4*x21;
        const dstype x23 = x22*x15;
        const dstype x24 = x17 - x20 + 2*x23;
        const dstype x25 = 0.5*(x10 + x3);
        const dstype x26 = uq3 - uq0*x25;
        const dstype x27 = Kokkos::pow(x26, 2);
        const dstype x28 = Kokkos::pow(mu3, 6);
        const dstype x29 = Kokkos::pow(x4, 3)*x28*Kokkos::pow(mu0, 3);
        const dstype x30 = x29*x27;
        const dstype x31 = x5*x30;
        const dstype x32 = Kokkos::pow(uq0, -4);
        const dstype x33 = x29*Kokkos::pow(x26, 3);
        const dstype x34 = Kokkos::sqrt(x5*x33);
        const dstype x35 = Kokkos::pow(mu1, -1);
        const dstype x36 = 110.4 + mu9;
        const dstype x37 = x4*x15;
        const dstype x38 = x37*x26;
        const dstype x39 = 1.0*mu0;
        const dstype x40 = Kokkos::pow(mu3, 2)*mu9;
        const dstype x41 = x40*x39;
        const dstype x42 = 110.4 + x41*x38;
        const dstype x43 = x36*x35/x42;
        const dstype x44 = x43/x34;
        const dstype x45 = (3*x31*x12 - 3*x32*x33)*x44;
        const dstype x46 = 0.333333333333333*x45;
        const dstype x47 = x46*x24;
        const dstype x48 = x4*x26;
        const dstype x49 = x2*x48;
        const dstype x50 = x37*x12;
        const dstype x51 = x34*x36*x35/Kokkos::pow(x42, 2);
        const dstype x52 = (-x41*x49 + x50*x41)*x51;
        const dstype x53 = 0.666666666666667*x52;
        const dstype x54 = x53*x24;
        const dstype x55 = x2*uq2;
        const dstype x56 = -x55*x14;
        const dstype x57 = x2*x22;
        const dstype x58 = x5*uq4;
        const dstype x59 = uq1*x58;
        const dstype x60 = x2*x19;
        const dstype x61 = x5*uq8;
        const dstype x62 = uq2*x61;
        const dstype x63 = x60 - x62;
        const dstype x64 = x43*x34;
        const dstype x65 = 0.666666666666667*x64;
        const dstype x66 = (x56 - 2*x57 + 2*x59 + x63)*x65;
        const dstype x67 = uq6 - uq4*x18;
        const dstype x68 = uq9 - uq8*x21;
        const dstype x69 = x67*x15 + x68*x15;
        const dstype x70 = 0.5*x45;
        const dstype x71 = x70*x69;
        const dstype x72 = x2*x68;
        const dstype x73 = uq1*x61;
        const dstype x74 = x2*x67;
        const dstype x75 = uq2*x58;
        const dstype x76 = 1.0*x64;
        const dstype x77 = (-x72 + x73 - x74 + x75)*x76;
        const dstype x78 = uq1*x55;
        const dstype x79 = 1.0*x69*x52;
        const dstype x80 = x71 + x77 - x78 - x79;
        const dstype x81 = Kokkos::pow(x4, -1);
        const dstype x82 = x2*x81*x52*x39;
        const dstype x83 = Kokkos::pow(mu2, -1);
        const dstype x84 = uq2*x74;
        const dstype x85 = uq1*x57;
        const dstype x86 = x4*(uq7 - uq4*x25 - (x84 + x85)*uq0);
        const dstype x87 = uq0*x86 - uq4*x48;
        const dstype x88 = x83*x87;
        const dstype x89 = x83*mu0;
        const dstype x90 = x81*x89;
        const dstype x91 = x87*x90;
        const dstype x92 = x2*x70;
        const dstype x93 = x76*x55;
        const dstype x94 = 2*x5;
        const dstype x95 = uq1*x94;
        const dstype x96 = uq2*x94;
        const dstype x97 = x0*x32;
        const dstype x98 = x7*x32;
        const dstype x99 = x4*uq0;
        const dstype x100 = x2*x76*x90;
        const dstype x101 = -x49 + x50 - x2*uq3;
        const dstype x102 = x2*uq1;
        const dstype x103 = x65*x102;
        const dstype x104 = x5*x64;
        const dstype x105 = 2.0*x104;
        const dstype x106 = x17 + 2*x20 - x23;
        const dstype x107 = x46*x106;
        const dstype x108 = x53*x106;
        const dstype x109 = x57 - x59;
        const dstype x110 = x65*(x109 + x56 - 2*x60 + 2*x62);
        const dstype x111 = x76*x102;
        const dstype x112 = uq2*x60;
        const dstype x113 = uq1*x72;
        const dstype x114 = x4*(uq11 - uq8*x25 - (x112 + x113)*uq0);
        const dstype x115 = uq0*x114 - uq8*x48;
        const dstype x116 = x83*x115;
        const dstype x117 = x65*x55;
        const dstype x118 = x90*x115;
        const dstype x119 = 1.0*x37;
        const dstype x120 = uq1*x119;
        const dstype x121 = -x120;
        const dstype x122 = x44*x30;
        const dstype x123 = 1.0*x122;
        const dstype x124 = x24*x123;
        const dstype x125 = uq1*x32;
        const dstype x126 = x124*x125;
        const dstype x127 = x51*x40;
        const dstype x128 = mu0*x127;
        const dstype x129 = 0.666666666666667*x128;
        const dstype x130 = x4*x129;
        const dstype x131 = x24*x130;
        const dstype x132 = x102*x131;
        const dstype x133 = 1.33333333333333*x64;
        const dstype x134 = x2*uq4;
        const dstype x135 = 1.5*x69;
        const dstype x136 = x122*x135;
        const dstype x137 = x125*x136;
        const dstype x138 = x2*uq8;
        const dstype x139 = 1.0*x138;
        const dstype x140 = x64*x139;
        const dstype x141 = 1.0*x4;
        const dstype x142 = x69*x128;
        const dstype x143 = x142*x141;
        const dstype x144 = x102*x143;
        const dstype x145 = -x137 - x140 + x144 + x18;
        const dstype x146 = 1.5*Kokkos::pow(x4, 2)*x44*x28*x27*Kokkos::pow(mu0, 4);
        const dstype x147 = x146/Kokkos::pow(uq0, 6);
        const dstype x148 = x88*x147;
        const dstype x149 = 1.0*Kokkos::pow(mu0, 2)*x127;
        const dstype x150 = x88*x149;
        const dstype x151 = x65*x15;
        const dstype x152 = Kokkos::pow(uq0, -5);
        const dstype x153 = x0*x152;
        const dstype x154 = 1.0*uq4;
        const dstype x155 = uq2*uq1;
        const dstype x156 = x152*x155;
        const dstype x157 = x5*x155;
        const dstype x158 = x38 + uq3*x15 - x136*x156 + x143*x157;
        const dstype x159 = x106*x123;
        const dstype x160 = x106*x130;
        const dstype x161 = x116*x149;
        const dstype x162 = x116*x147;
        const dstype x163 = x76*x15;
        const dstype x164 = x69*x163 - x78*x141;
        const dstype x165 = uq2*x32;
        const dstype x166 = x65*(x138 + x16);
        const dstype x167 = uq2*x119;
        const dstype x168 = -x167;
        const dstype x169 = x55*x130;
        const dstype x170 = x165*x136;
        const dstype x171 = x55*x143;
        const dstype x172 = x2*x64*x154;
        const dstype x173 = -x170 + x171 - x172 + x21;
        const dstype x174 = x7*x152;
        const dstype x175 = x165*x159;
        const dstype x176 = x106*x169;
        const dstype x177 = x65*(-2*x138 + x16);
        const dstype x178 = x44*x31;
        const dstype x179 = 1.0*x178;
        const dstype x180 = x37*x129;
        const dstype x181 = -x119*x142 + x178*x135;
        const dstype x182 = x146*x152;
        const dstype x183 = x15 + x37;
        const dstype x184 = x5*x149;
        const dstype x185 = x102*x133;
        const dstype x186 = -x93;
        const dstype x187 = x100*(-x48 + x99*(x11 - (-x6 - x8)*uq0));
        const dstype x188 = -0.333333333333333*x104*x155;
        const dstype x189 = v0 + x15*x133;
        const dstype x190 = -x89*x111;
        const dstype x191 = -x151;
        const dstype x192 = v0 + x163;
        const dstype x193 = -x89*x93;
        const dstype x194 = v0 + x89*x163;
        const dstype x195 = -x111;
        const dstype x196 = x55*x133;

        f[0] = 0;
        f[1] = x13 - x3 + x47 - x54 + x66;
        f[2] = x80;
        f[3] = uq1*x101 + x100*(x86 - uq4*x13 + x99*(-x84 - x85 - x9*uq4 - (uq4*x97 + uq4*x98 - x67*x96 - x95*x22)*uq0)) - x24*x103 + x47*x21 - x54*x21 + x66*x21 - x69*x93 + x71*x18 + x77*x18 - x79*x18 - x82*x88 - x91*x105 + x92*x91;
        f[4] = 0;
        f[5] = x80;
        f[6] = -x10 + x107 - x108 + x110 + x13;
        f[7] = uq2*x101 + x100*(x114 - uq8*x13 + x99*(-x112 - x113 - x9*uq8 - (uq8*x97 + uq8*x98 - x68*x95 - x96*x19)*uq0)) - x105*x118 - x106*x117 + x18*x107 - x18*x108 + x18*x110 - x69*x111 + x71*x21 + x77*x21 - x79*x21 - x82*x116 + x92*x118;
        f[8] = 1;
        f[9] = x121 - x126 + x132 + 2*x21 - x133*x134;
        f[10] = x145;
        f[11] = x158 - uq1*x148 + x100*(uq4*x120 + x99*(-uq0*x109 - x102*x154)) - x124*x153 + x125*x150 + x24*x151 - x3*x141 - x59*x133 + x6*x131 - x76*x62;
        f[12] = 0;
        f[13] = x145;
        f[14] = x121 + x102*x160 - x125*x159 + x65*x134;
        f[15] = x164 - uq1*x162 + x100*(uq8*x120 + x99*(-uq1*x139 - (x72 - x73)*uq0)) + x125*x161 - x136*x153 - x156*x159 + x160*x157 + x6*x143 - x73*x76 + x75*x65;
        f[16] = 0;
        f[17] = x166 + x168 - x124*x165 + x24*x169;
        f[18] = x173;
        f[19] = x164 - uq2*x148 + x100*(uq4*x167 + x99*(-x55*x154 - (x74 - x75)*uq0)) - x124*x156 + x131*x157 + x165*x150 - x174*x136 + x21*x166 - x75*x76 + x8*x143;
        f[20] = 1;
        f[21] = x173;
        f[22] = x168 - x175 + x176 + x177 + 2*x18;
        f[23] = x158 - uq2*x162 - x10*x141 + x100*(uq8*x167 + x99*(-uq0*x63 - uq2*x139)) + x106*x151 + x161*x165 - x174*x159 + x18*x177 - x76*x59 + x8*x160;
        f[24] = 0;
        f[25] = x4 + x24*x179 - x24*x180;
        f[26] = x181;
        f[27] = x126 - x132 + x170 - x171 + uq1*x183 + x88*x182 - x88*x184 - x89*x172;
        f[28] = 0;
        f[29] = x181;
        f[30] = x4 + x106*x179 - x106*x180;
        f[31] = x137 - x144 + x175 - x176 + uq2*x183 + x116*x182 - x116*x184 - x89*x140;
        f[32] = v0;
        f[33] = -x185;
        f[34] = x186;
        f[35] = x187 - x6*x133 - x8*x76;
        f[36] = 0;
        f[37] = x186;
        f[38] = x103;
        f[39] = x188;
        f[40] = 0;
        f[41] = x189;
        f[42] = 0;
        f[43] = x185 + x190;
        f[44] = 0;
        f[45] = 0;
        f[46] = x191;
        f[47] = -x117;
        f[48] = 0;
        f[49] = 0;
        f[50] = x192;
        f[51] = x193 + x93;
        f[52] = 0;
        f[53] = x163;
        f[54] = 0;
        f[55] = x111;
        f[56] = 0;
        f[57] = 0;
        f[58] = 0;
        f[59] = x194;
        f[60] = 0;
        f[61] = 0;
        f[62] = 0;
        f[63] = 0;
        f[64] = 0;
        f[65] = x117;
        f[66] = x195;
        f[67] = x188;
        f[68] = v0;
        f[69] = x195;
        f[70] = -x196;
        f[71] = x187 - x6*x76 - x8*x133;
        f[72] = 0;
        f[73] = 0;
        f[74] = x163;
        f[75] = x93;
        f[76] = 0;
        f[77] = x192;
        f[78] = 0;
        f[79] = x111 + x190;
        f[80] = 0;
        f[81] = x191;
        f[82] = 0;
        f[83] = -x103;
        f[84] = 0;
        f[85] = 0;
        f[86] = x189;
        f[87] = x193 + x196;
        f[88] = 0;
        f[89] = 0;
        f[90] = 0;
        f[91] = 0;
        f[92] = 0;
        f[93] = 0;
        f[94] = 0;
        f[95] = x194;
    }

    KOKKOS_INLINE_FUNCTION static
    void source_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x1 = x[1];
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(x1, -1);
        const dstype x2 = Kokkos::pow(uq0, -1);
        const dstype x3 = x2*uq2;
        const dstype x4 = uq6 - x3*uq4;
        const dstype x5 = x2*uq1;
        const dstype x6 = uq9 - x5*uq8;
        const dstype x7 = x2*x4 + x2*x6;
        const dstype x8 = Kokkos::pow(uq1, 2);
        const dstype x9 = Kokkos::pow(uq0, -3);
        const dstype x10 = x8*x9;
        const dstype x11 = Kokkos::pow(uq2, 2);
        const dstype x12 = x9*x11;
        const dstype x13 = 0.5*(-2*x10 - 2*x12);
        const dstype x14 = Kokkos::pow(uq0, -2);
        const dstype x15 = x14*x11;
        const dstype x16 = x8*x14;
        const dstype x17 = -0.5*x15 - 0.5*x16;
        const dstype x18 = x17 - uq0*x13;
        const dstype x19 = 0.5*(x15 + x16);
        const dstype x20 = uq3 - uq0*x19;
        const dstype x21 = Kokkos::pow(x20, 2);
        const dstype x22 = Kokkos::pow(mu3, 6);
        const dstype x23 = -1.0 + mu0;
        const dstype x24 = x22*Kokkos::pow(x23, 3)*Kokkos::pow(mu0, 3);
        const dstype x25 = x24*x21;
        const dstype x26 = x9*x25;
        const dstype x27 = Kokkos::pow(uq0, -4);
        const dstype x28 = x24*Kokkos::pow(x20, 3);
        const dstype x29 = Kokkos::sqrt(x9*x28);
        const dstype x30 = Kokkos::pow(mu1, -1);
        const dstype x31 = 110.4 + mu9;
        const dstype x32 = x2*x23;
        const dstype x33 = x32*x20;
        const dstype x34 = 1.0*mu0;
        const dstype x35 = Kokkos::pow(mu3, 2)*mu9;
        const dstype x36 = x34*x35;
        const dstype x37 = 110.4 + x33*x36;
        const dstype x38 = x30*x31/x37;
        const dstype x39 = x38/x29;
        const dstype x40 = (3*x26*x18 - 3*x28*x27)*x39;
        const dstype x41 = 0.5*x40;
        const dstype x42 = x6*x14;
        const dstype x43 = x9*uq8;
        const dstype x44 = uq1*x43;
        const dstype x45 = x9*uq4;
        const dstype x46 = uq2*x45;
        const dstype x47 = x38*x29;
        const dstype x48 = 1.0*x47;
        const dstype x49 = uq2*x14;
        const dstype x50 = uq1*x49;
        const dstype x51 = x23*x20;
        const dstype x52 = x51*x14;
        const dstype x53 = x32*x18;
        const dstype x54 = x30*x31*x29/Kokkos::pow(x37, 2);
        const dstype x55 = (-x52*x36 + x53*x36)*x54;
        const dstype x56 = x0*x2;
        const dstype x57 = uq5 - x5*uq4;
        const dstype x58 = -x2*x57;
        const dstype x59 = uq10 - x3*uq8;
        const dstype x60 = x2*x59;
        const dstype x61 = x58 + 2*x60 + uq2*x56;
        const dstype x62 = 0.333333333333333*x40;
        const dstype x63 = x61*x62;
        const dstype x64 = x0*x49;
        const dstype x65 = x59*x14;
        const dstype x66 = uq2*x43;
        const dstype x67 = x65 - x66;
        const dstype x68 = -uq1*x45 + x57*x14;
        const dstype x69 = 0.666666666666667*x47;
        const dstype x70 = 0.666666666666667*x55;
        const dstype x71 = x70*x61;
        const dstype x72 = (-x64 - 2*x65 + 2*x66 + x68)*x69;
        const dstype x73 = 2*x56;
        const dstype x74 = x58 - x60 - uq2*x73;
        const dstype x75 = x61*x69;
        const dstype x76 = 2.0*x47;
        const dstype x77 = Kokkos::pow(x23, -1);
        const dstype x78 = Kokkos::pow(mu2, -1);
        const dstype x79 = x78*mu0;
        const dstype x80 = x79*x77;
        const dstype x81 = uq2*x65;
        const dstype x82 = uq1*x42;
        const dstype x83 = x23*(uq11 - uq8*x19 - (x81 + x82)*uq0);
        const dstype x84 = uq0*x83 - uq8*x51;
        const dstype x85 = x9*x84;
        const dstype x86 = x84*x14;
        const dstype x87 = 2*x9;
        const dstype x88 = uq8*x27;
        const dstype x89 = uq0*x23;
        const dstype x90 = x48*x14;
        const dstype x91 = x80*x90;
        const dstype x92 = uq1*x27;
        const dstype x93 = 1.5*x7;
        const dstype x94 = x39*x25;
        const dstype x95 = x93*x94;
        const dstype x96 = uq8*x14;
        const dstype x97 = 1.0*x96;
        const dstype x98 = x97*x47;
        const dstype x99 = 1.0*x23;
        const dstype x100 = x54*x35;
        const dstype x101 = mu0*x100;
        const dstype x102 = x7*x101;
        const dstype x103 = x99*x102;
        const dstype x104 = uq1*x14;
        const dstype x105 = 1.0*x94;
        const dstype x106 = x92*x105;
        const dstype x107 = 0.666666666666667*x101;
        const dstype x108 = x23*x107;
        const dstype x109 = x61*x108;
        const dstype x110 = x74*x108;
        const dstype x111 = x9*uq2;
        const dstype x112 = Kokkos::pow(uq0, -5);
        const dstype x113 = x61*x105*x112;
        const dstype x114 = 1.0*x78*Kokkos::pow(mu0, 2)*x100;
        const dstype x115 = x84*x114;
        const dstype x116 = 1.5*x84*x78*x39*x22*Kokkos::pow(x23, 2)*x21*Kokkos::pow(mu0, 4);
        const dstype x117 = x116/Kokkos::pow(uq0, 6);
        const dstype x118 = 1.0*x32;
        const dstype x119 = uq8*x118;
        const dstype x120 = uq2*x27;
        const dstype x121 = x105*x120;
        const dstype x122 = x61*x121;
        const dstype x123 = x49*x109;
        const dstype x124 = (x56 - 2*x96)*x69;
        const dstype x125 = x39*x26;
        const dstype x126 = 1.0*x125;
        const dstype x127 = x32*x107;
        const dstype x128 = x0*uq1;
        const dstype x129 = x90*x128;
        const dstype x130 = 1.33333333333333*x47;
        const dstype x131 = x2*x48;

        f[0] = 0;
        f[1] = -x0*(-x50 + x48*(-x42 + x44 + x46 - x4*x14) + x7*x41 - 1.0*x7*x55);
        f[2] = -x0*(-x15 + x63 - x71 + x72 - x69*(2*x64 + x67 + x68) + x70*x74 - x74*x62);
        f[3] = -x0*(uq2*(-x52 + x53 - uq3*x14) + x3*x63 - x3*x71 + x3*x72 - x75*x49 + x91*(x83 + x89*(-x81 - x82 - uq0*(x8*x88 + x88*x11 - uq2*x87*x59 - x6*uq1*x87) - uq8*x13) - uq8*x23*x18) - x80*x85*x76 + x80*x86*x41 - x86*x78*x77*x55*x34);
        f[4] = 0;
        f[5] = -x0*(x3 - x98 + x103*x104 - x92*x95);
        f[6] = -x0*(-x104*x110 + x109*x104 - x61*x106 + x74*x106);
        f[7] = -x0*(-uq1*x117 - x50*x99 + x69*x46 + x91*(uq1*x119 + x89*(-uq1*x97 - (x42 - x44)*uq0)) + x92*x115 + uq1*x109*x111 - uq2*uq1*x113);
        f[8] = -x0;
        f[9] = -x0*(x5 - uq4*x90 + x49*x103 - x95*x120);
        f[10] = -x0*(-x122 + x123 + x124 + 2*x3 - x49*x110 + x74*x121 - (-x73 + x96)*x69);
        f[11] = -x0*(x33 - uq2*x117 - x11*x113 + x115*x120 + x12*x109 + x2*uq3 + x2*x75 + x3*x124 + x91*(uq2*x119 + (-uq0*x67 - uq2*x97)*x89) - x99*x15);
        f[12] = 0;
        f[13] = -x0*(-x102*x118 + x93*x125);
        f[14] = -(x61*x126 - x61*x127 - x74*x126 + x74*x127)*x0;
        f[15] = -x0*(x122 - x123 + uq2*(x2 + x32) + x112*x116 - x79*x98 - x85*x114);
        f[16] = 0;
        f[17] = x64*x48;
        f[18] = 0;
        f[19] = -x69*x111*x128;
        f[20] = 0;
        f[21] = 0;
        f[22] = 0;
        f[23] = x64*x69;
        f[24] = 0;
        f[25] = -x56*x48;
        f[26] = 0;
        f[27] = 0;
        f[28] = 0;
        f[29] = 0;
        f[30] = 0;
        f[31] = 0;
        f[32] = -v0*x0;
        f[33] = x129;
        f[34] = x76*x64;
        f[35] = -x0*(-x12*x130 + x91*(-x51 + x89*(x17 - (-x10 - x12)*uq0)));
        f[36] = 0;
        f[37] = -x0*(v0 + x131);
        f[38] = 0;
        f[39] = x79*x129;
        f[40] = 0;
        f[41] = 0;
        f[42] = -x0*(v0 + x2*x76);
        f[43] = -x0*(x49*x130 - x79*x48*x49);
        f[44] = 0;
        f[45] = 0;
        f[46] = 0;
        f[47] = -x0*(v0 + x79*x131);
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 1;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 3) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 4) {
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];

            f[0] = tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = tau0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = tau0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = tau0;
            f[16] = n0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = n0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = n0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = n0;
            f[32] = n1;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = n1;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = n1;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = n1;
        }
        else if (ib == 5) {
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];

            const dstype x0 = -n1*n0*tau0;

            f[0] = tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = tau0*(1 - Kokkos::pow(n0, 2));
            f[6] = x0;
            f[7] = 0;
            f[8] = 0;
            f[9] = x0;
            f[10] = tau0*(1 - Kokkos::pow(n1, 2));
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = tau0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 2) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 3) {
            const dstype mu8 = mu[8];
            const dstype mu9 = mu[9];
            const dstype mu10 = mu[10];

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = mu8*mu10/mu9;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 4) {
            const dstype tau0 = tau[0];

            const dstype x0 = -tau0;

            f[0] = x0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = x0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = x0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = x0;
        }
        else if (ib == 5) {
            const dstype tau0 = tau[0];

            const dstype x0 = -tau0;

            f[0] = x0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = x0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = x0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = x0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fint(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x1 = x[1];
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype n0 = n[0];
        const dstype n1 = n[1];
        const dstype tau0 = tau[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = -1.0 + mu0;
        const dstype x2 = Kokkos::pow(uhat0, -2);
        const dstype x3 = 0.5*(x2*Kokkos::pow(uhat1, 2) + x2*Kokkos::pow(uhat2, 2));
        const dstype x4 = uhat3 - x3*uhat0;
        const dstype x5 = x0*x4;
        const dstype x6 = Kokkos::pow(uhat0, -1);
        const dstype x7 = x6*uq8;
        const dstype x8 = uq10 - x7*uhat2;
        const dstype x9 = x2*uhat2;
        const dstype x10 = uq9 - x7*uhat1;
        const dstype x11 = x2*uhat1;
        const dstype x12 = x0*uhat0;
        const dstype x13 = 110.4 + mu9;
        const dstype x14 = 1.0*mu0;
        const dstype x15 = Kokkos::pow(mu3, 2)*mu9;
        const dstype x16 = Kokkos::sqrt(Kokkos::pow(x0, 3)*Kokkos::pow(x4, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3)/Kokkos::pow(uhat0, 3))/(110.4 + x6*x5*x15*x14);
        const dstype x17 = x2*x14*x13*x16/(x0*mu2*mu1);
        const dstype x18 = x6*uq4;
        const dstype x19 = uq6 - x18*uhat2;
        const dstype x20 = uq5 - x18*uhat1;
        const dstype x21 = Kokkos::sqrt(Kokkos::pow(mu9, 3));
        const dstype x22 = x21*x15*mu0*mu1/x13;
        const dstype x23 = Kokkos::pow(uq0, -2);
        const dstype x24 = x6*uhat2/x1;
        const dstype x25 = x6*x8;
        const dstype x26 = x6*x20;
        const dstype x27 = x21*x16;
        const dstype x28 = 0.000982141192491313*x27;

        f[0] = 0.000418426671846558*x22*(tau0*(-uhat3 + uq3) + n0*x17*(x12*(uq7 - uhat0*(x20*x11 + x9*x19) - x3*uq4) - x5*uq4) + n1*x17*(x12*(uq11 - uhat0*(x11*x10 + x8*x9) - x3*uq8) - x5*uq8));
        f[1] = 4.14087039670808e-07*x0*x22*(uq3 - 0.5*(Kokkos::pow(uq1, 2)*x23 + Kokkos::pow(uq2, 2)*x23)*uq0);
        f[2] = x28*(x24 - x25 + 2*x26);
        f[3] = 0.00147321178873697*(x6*x10 + x6*x19)*x27;
        f[4] = x28*(x24 + 2*x25 - x26);
    }

    KOKKOS_INLINE_FUNCTION static
    void fint_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype n0 = n[0];
        const dstype n1 = n[1];
        const dstype tau0 = tau[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uq1, 2);
        const dstype x1 = 2/Kokkos::pow(uq0, 3);
        const dstype x2 = Kokkos::pow(uq2, 2);
        const dstype x3 = 0.5/Kokkos::pow(uq0, 2);
        const dstype x4 = -1.0 + mu0;
        const dstype x5 = Kokkos::sqrt(Kokkos::pow(mu9, 3));
        const dstype x6 = Kokkos::pow(mu3, 2)*mu9;
        const dstype x7 = x6*mu0;
        const dstype x8 = x5*x7*mu1/(110.4 + mu9);
        const dstype x9 = 4.14087039670808e-07*x4*x8;
        const dstype x10 = x9/uq0;
        const dstype x11 = Kokkos::pow(uhat0, -2);
        const dstype x12 = Kokkos::pow(uhat0, -1);
        const dstype x13 = Kokkos::pow(uhat2, 2);
        const dstype x14 = x13*x11;
        const dstype x15 = Kokkos::pow(uhat1, 2);
        const dstype x16 = x15*x11;
        const dstype x17 = uhat3 - 0.5*(x14 + x16)*uhat0;
        const dstype x18 = x4*x17;
        const dstype x19 = Kokkos::pow(uhat0, -3);
        const dstype x20 = x5*Kokkos::sqrt(Kokkos::pow(x4, 3)*x19*Kokkos::pow(x17, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3))/(110.4 + 1.0*x7*x12*x18);
        const dstype x21 = x20*x11;
        const dstype x22 = 0.000418426671846558*x6*Kokkos::pow(mu0, 2)/mu2;
        const dstype x23 = x22*x21;
        const dstype x24 = n0*x23;
        const dstype x25 = (-x18 + x4*uhat0*(-0.5*x14 - 0.5*x16 - (-x13*x19 - x15*x19)*uhat0))/x4;
        const dstype x26 = 0.00196428238498263*x21;
        const dstype x27 = 0.00147321178873697*x21;
        const dstype x28 = 0.000982141192491313*x21;
        const dstype x29 = x20*x12;
        const dstype x30 = 0.00196428238498263*x29;
        const dstype x31 = -0.000982141192491313*x29;
        const dstype x32 = 0.00147321178873697*x29;
        const dstype x33 = x22*x29;
        const dstype x34 = n1*x23;

        f[0] = 0;
        f[1] = x9*(-x0*x3 - x2*x3 - 0.5*(-x0*x1 - x2*x1)*uq0);
        f[2] = 0;
        f[3] = 0;
        f[4] = 0;
        f[5] = 0;
        f[6] = -uq1*x10;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = 0;
        f[11] = -uq2*x10;
        f[12] = 0;
        f[13] = 0;
        f[14] = 0;
        f[15] = 0.000418426671846558*x8*tau0;
        f[16] = x9;
        f[17] = 0;
        f[18] = 0;
        f[19] = 0;
        f[20] = x24*x25;
        f[21] = 0;
        f[22] = -x26*uhat1;
        f[23] = -x27*uhat2;
        f[24] = x28*uhat1;
        f[25] = -x24*uhat1;
        f[26] = 0;
        f[27] = x30;
        f[28] = 0;
        f[29] = x31;
        f[30] = -x24*uhat2;
        f[31] = 0;
        f[32] = 0;
        f[33] = x32;
        f[34] = 0;
        f[35] = n0*x33;
        f[36] = 0;
        f[37] = 0;
        f[38] = 0;
        f[39] = 0;
        f[40] = x34*x25;
        f[41] = 0;
        f[42] = x28*uhat2;
        f[43] = -x27*uhat1;
        f[44] = -x26*uhat2;
        f[45] = -x34*uhat1;
        f[46] = 0;
        f[47] = 0;
        f[48] = x32;
        f[49] = 0;
        f[50] = -x34*uhat2;
        f[51] = 0;
        f[52] = x31;
        f[53] = 0;
        f[54] = x30;
        f[55] = n1*x33;
        f[56] = 0;
        f[57] = 0;
        f[58] = 0;
        f[59] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fint_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x1 = x[1];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype n0 = n[0];
        const dstype n1 = n[1];
        const dstype tau0 = tau[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = -1.0 + mu0;
        const dstype x2 = Kokkos::pow(x0, -1);
        const dstype x3 = Kokkos::pow(uhat0, -2);
        const dstype x4 = Kokkos::pow(uhat2, 2);
        const dstype x5 = x4*x3;
        const dstype x6 = Kokkos::pow(uhat1, 2);
        const dstype x7 = x3*x6;
        const dstype x8 = 0.5*(x5 + x7);
        const dstype x9 = uhat3 - x8*uhat0;
        const dstype x10 = x0*x9;
        const dstype x11 = Kokkos::pow(uhat0, -1);
        const dstype x12 = uq4*x11;
        const dstype x13 = x12*uhat2;
        const dstype x14 = uq6 - x13;
        const dstype x15 = x3*x14;
        const dstype x16 = x15*uhat2;
        const dstype x17 = x12*uhat1;
        const dstype x18 = uq5 - x17;
        const dstype x19 = x3*x18;
        const dstype x20 = x19*uhat1;
        const dstype x21 = x0*(uq7 - x8*uq4 - (x16 + x20)*uhat0);
        const dstype x22 = -uq4*x10 + x21*uhat0;
        const dstype x23 = 1.0*mu0;
        const dstype x24 = Kokkos::pow(mu3, 2)*mu9;
        const dstype x25 = x24*x23;
        const dstype x26 = x25*x11;
        const dstype x27 = 110.4 + x26*x10;
        const dstype x28 = Kokkos::pow(x27, -1);
        const dstype x29 = Kokkos::pow(uhat0, -3);
        const dstype x30 = Kokkos::pow(mu3, 6);
        const dstype x31 = Kokkos::pow(x0, 3)*x30*Kokkos::pow(mu0, 3);
        const dstype x32 = Kokkos::pow(x9, 3)*x31;
        const dstype x33 = Kokkos::sqrt(x32*x29);
        const dstype x34 = x33*x28;
        const dstype x35 = x34*mu0;
        const dstype x36 = 110.4 + mu9;
        const dstype x37 = x36/(mu2*mu1);
        const dstype x38 = n0*x37;
        const dstype x39 = x35*x38;
        const dstype x40 = 2.0*x29;
        const dstype x41 = 2*x29;
        const dstype x42 = 0.5*(-x4*x41 - x6*x41);
        const dstype x43 = x41*uhat1;
        const dstype x44 = x41*uhat2;
        const dstype x45 = Kokkos::pow(uhat0, -4);
        const dstype x46 = x6*x45;
        const dstype x47 = x4*x45;
        const dstype x48 = x0*uhat0;
        const dstype x49 = -0.5*x5 - 0.5*x7 - x42*uhat0;
        const dstype x50 = x0*x49;
        const dstype x51 = x2*x38;
        const dstype x52 = x3*x23;
        const dstype x53 = x52*x34;
        const dstype x54 = x53*x51;
        const dstype x55 = x51*x22;
        const dstype x56 = Kokkos::pow(x9, 2);
        const dstype x57 = x56*x31;
        const dstype x58 = x57*x29;
        const dstype x59 = -3*x45*x32 + 3*x58*x49;
        const dstype x60 = Kokkos::pow(x33, -1);
        const dstype x61 = x60*x28;
        const dstype x62 = 0.5*x3*x61*x59*mu0;
        const dstype x63 = n1*x37;
        const dstype x64 = x63*x35;
        const dstype x65 = uq8*x11;
        const dstype x66 = x65*uhat2;
        const dstype x67 = uq10 - x66;
        const dstype x68 = x3*x67;
        const dstype x69 = x68*uhat2;
        const dstype x70 = x65*uhat1;
        const dstype x71 = uq9 - x70;
        const dstype x72 = x3*x71;
        const dstype x73 = x72*uhat1;
        const dstype x74 = x0*(uq11 - x8*uq8 - (x69 + x73)*uhat0);
        const dstype x75 = -uq8*x10 + x74*uhat0;
        const dstype x76 = x2*x75;
        const dstype x77 = x50*x26 - x3*x25*x10;
        const dstype x78 = x33/Kokkos::pow(x27, 2);
        const dstype x79 = x78*x77*x52;
        const dstype x80 = x76*x63;
        const dstype x81 = x2*x63*x53;
        const dstype x82 = Kokkos::sqrt(Kokkos::pow(mu9, 3));
        const dstype x83 = x24*mu0;
        const dstype x84 = 0.000418426671846558*x82*x83*mu1/x36;
        const dstype x85 = Kokkos::pow(x1, -1);
        const dstype x86 = x85*x11;
        const dstype x87 = x86*uhat2;
        const dstype x88 = x67*x11;
        const dstype x89 = x11*x18;
        const dstype x90 = x87 - x88 + 2*x89;
        const dstype x91 = x82*x28;
        const dstype x92 = x60*x91;
        const dstype x93 = x59*x92;
        const dstype x94 = 0.000491070596245657*x93;
        const dstype x95 = x3*uhat2;
        const dstype x96 = -x85*x95;
        const dstype x97 = uq8*x29;
        const dstype x98 = x68 - x97*uhat2;
        const dstype x99 = x91*x33;
        const dstype x100 = 0.000982141192491313*x99;
        const dstype x101 = x82*x78;
        const dstype x102 = x77*x101;
        const dstype x103 = 0.000982141192491313*x102;
        const dstype x104 = x14*x11 + x71*x11;
        const dstype x105 = x97*uhat1;
        const dstype x106 = uq4*x29;
        const dstype x107 = x106*uhat2;
        const dstype x108 = 0.00147321178873697*x99;
        const dstype x109 = 0.00147321178873697*x104;
        const dstype x110 = x87 + 2*x88 - x89;
        const dstype x111 = x19 - x106*uhat1;
        const dstype x112 = x38*x22;
        const dstype x113 = x112*uhat1;
        const dstype x114 = 1.0*x78*x24*Kokkos::pow(mu0, 2);
        const dstype x115 = x45*x114;
        const dstype x116 = x3*uq8;
        const dstype x117 = 1.0*x116;
        const dstype x118 = 1.0*x0;
        const dstype x119 = 1.0*uq4;
        const dstype x120 = x3*x119;
        const dstype x121 = 1.5*Kokkos::pow(x0, 2)*x61*x56*x30*Kokkos::pow(mu0, 4);
        const dstype x122 = x121/Kokkos::pow(uhat0, 6);
        const dstype x123 = x75*x63;
        const dstype x124 = x123*uhat1;
        const dstype x125 = x90*uhat1;
        const dstype x126 = x57*x92;
        const dstype x127 = x45*x126;
        const dstype x128 = 0.00147321178873697*x127;
        const dstype x129 = x3*uq4;
        const dstype x130 = x0*x83*x101;
        const dstype x131 = 0.000982141192491313*x130;
        const dstype x132 = x3*x131;
        const dstype x133 = 0.00220981768310546*x104;
        const dstype x134 = x109*x130;
        const dstype x135 = x110*uhat1;
        const dstype x136 = x45*uhat2;
        const dstype x137 = x114*x136;
        const dstype x138 = x122*uhat2;
        const dstype x139 = x126*x136;
        const dstype x140 = 0.00147321178873697*x139;
        const dstype x141 = x95*x131;
        const dstype x142 = x121/Kokkos::pow(uhat0, 5);
        const dstype x143 = x29*x114;
        const dstype x144 = x58*x92;
        const dstype x145 = 0.00147321178873697*x144;
        const dstype x146 = x11*x130;
        const dstype x147 = 0.000982141192491313*x146;

        f[0] = x84*(x54*(x21 - uq4*x50 + x48*(-x16 - x20 - uq4*x42 - (uq4*x46 + uq4*x47 - x43*x18 - x44*x14)*uhat0)) + x62*x55 - x79*x55 + x80*x62 - x80*x79 + x81*(x74 - uq8*x50 + x48*(-x69 - x73 - uq8*x42 - (uq8*x46 + uq8*x47 - x67*x44 - x71*x43)*uhat0)) - x76*x64*x40 - x2*x40*x39*x22);
        f[1] = 0;
        f[2] = x100*(-2*x19 + x96 + x98 + uq4*x43) - x90*x103 + x90*x94;
        f[3] = -x102*x109 + 0.000736605894368485*x93*x104 + (x105 + x107 - x15 - x72)*x108;
        f[4] = x100*(x111 - 2*x68 + x96 + uq8*x44) - x103*x110 + x94*x110;
        f[5] = x84*(x113*x115 - x113*x122 + x115*x124 - x124*x122 + x54*(x17*x118 + (-x111*uhat0 - x120*uhat1)*x48) + x81*(x48*(-x117*uhat1 - (-x105 + x72)*uhat0) + x70*x118));
        f[6] = 0;
        f[7] = x125*x132 - x128*x125 - 0.00196428238498263*x99*x129;
        f[8] = -x108*x116 - x127*x133*uhat1 + x3*x134*uhat1;
        f[9] = x100*x129 - x128*x135 + x132*x135;
        f[10] = x84*(x112*x137 - x112*x138 + x123*x137 - x123*x138 + x54*(x13*x118 + x48*(-x95*x119 - (-x107 + x15)*uhat0)) + x81*(x48*(-x117*uhat2 - x98*uhat0) + x66*x118));
        f[11] = 0;
        f[12] = x100*(x116 + x86) - x90*x140 + x90*x141;
        f[13] = -x108*x129 - x133*x139 + x95*x134;
        f[14] = x100*(-2*x116 + x86) - x110*x140 + x110*x141;
        f[15] = x84*(-tau0 + x112*x142 - x112*x143 + x123*x142 - x123*x143 - x39*x120 - x64*x117);
        f[16] = 0;
        f[17] = x90*x145 - x90*x147;
        f[18] = -x109*x146 + x133*x144;
        f[19] = x110*x145 - x110*x147;
    }

    KOKKOS_INLINE_FUNCTION static
    void fext(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype uext[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype uext0 = uext[0];
        const dstype mu8 = mu[8];
        const dstype mu9 = mu[9];

        f[0] = -uhat0 + uq0;
        f[1] = -uhat1;
        f[2] = -uhat2;
        f[3] = -uhat3 + mu8*uhat0*uext0/mu9;
    }

    KOKKOS_INLINE_FUNCTION static
    void fext_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype uext[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 1;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
        f[4] = 0;
        f[5] = 0;
        f[6] = 0;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = 0;
        f[11] = 0;
        f[12] = 0;
        f[13] = 0;
        f[14] = 0;
        f[15] = 0;
        f[16] = 0;
        f[17] = 0;
        f[18] = 0;
        f[19] = 0;
        f[20] = 0;
        f[21] = 0;
        f[22] = 0;
        f[23] = 0;
        f[24] = 0;
        f[25] = 0;
        f[26] = 0;
        f[27] = 0;
        f[28] = 0;
        f[29] = 0;
        f[30] = 0;
        f[31] = 0;
        f[32] = 0;
        f[33] = 0;
        f[34] = 0;
        f[35] = 0;
        f[36] = 0;
        f[37] = 0;
        f[38] = 0;
        f[39] = 0;
        f[40] = 0;
        f[41] = 0;
        f[42] = 0;
        f[43] = 0;
        f[44] = 0;
        f[45] = 0;
        f[46] = 0;
        f[47] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fext_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype uext[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uext0 = uext[0];
        const dstype mu8 = mu[8];
        const dstype mu9 = mu[9];

        f[0] = -1;
        f[1] = 0;
        f[2] = 0;
        f[3] = mu8*uext0/mu9;
        f[4] = 0;
        f[5] = -1;
        f[6] = 0;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = -1;
        f[11] = 0;
        f[12] = 0;
        f[13] = 0;
        f[14] = 0;
        f[15] = -1;
    }

};
